ResearchKit/ResearchKit

- docs/Survey/CreatingSurveys-template.markdown
-The code isn't formatting correctly in section 2. By adding a closing p tag, the documentation can be read more easily.
After:
Before:
> Add closing p tag to fix formatting in section 2

- ResearchKit/Common/ORKFormStep.m
[Coding Guidelines for Cocoa](https://developer.apple.com/library/mac/documentation/Cocoa/Conceptual/CodingGuidelines/Articles/NamingMethods.html#//apple_ref/doc/uid/20001282-BCIGIJJF
)
> Remove spaces according to Apple's cocoa coding style.

- ResearchKit/Common/ORKResult.m
- ResearchKitTests/ORKRecorderTests.m
Removed space between colon and parameters according to  cocoa coding style guide.
This issue is related to pull #26 .
> Removed spaces between colon and parameters according to Apple's cocoa coding style.

- ResearchKit/ActiveTasks/ORKAudioStepViewController.m
This PR is to avoid a retain cycle in the `ORKAudioStepViewController`
> Avoid retain cycle

- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKHealthAnswerFormat.m
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKTaskViewController.m
While the current way of checking for the version is not deprecated,
converting the system version string to float isn’t a good idea either.
The framework is for iOS 8 and above, so we can use the new Foundation API.
> Uses modern version detection API instead of floating point comparison.

- README.md
"cases" should be capitalized correctly in the "Use cases" header in the README.
> Capitalization Consistency of sections in README

- ResearchKit/ActiveTasks/ORKDataLogger.m
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Consent/ORKConsentSignature.m
- ResearchKit/Consent/ORKEAGLMoviePlayerView.m
Updating (id)init... methods to return instancetype instead of id.  initWithCoder: still returns (id) so those were left alone.
> Updating init methods that return id to return instancetype instead.

- ResearchKit.podspec
Fixed an inconsistency between the podspec, which was looking for a tag named `v1.0.0`, and the tag's actual name `1.0.0`.
> [Podspec] Fixed tag naming

- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
fixes a typo in a comment in `samples/ORKCatalog/ORKCatalog/TaskListRow.swift` from `Surevey` to `Survey`
> corrects typo in a comment

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKQuestionStep.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKQuestionStep_Internal.h
- ResearchKit/Common/ORKScaleSlider.h
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKScaleSliderView.m
- ResearchKit/Common/ORKSurveyAnswerCellForScale.h
- ResearchKit/Common/ORKSurveyAnswerCellForScale.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
I have implemented vertical scale support ([issue #3](https://github.com/ResearchKit/ResearchKit/issues/3)).
`ORKScaleSlider` now has the `isVertical` property. When set to `YES`, it internally uses the `UIView`'s`transform` property and some minor *bounds* and *touch* trickery to draw and work in vertical.
`ORKScaleSliderView` now has vertical support through the use of the new `isVertical` method from the `ORKScaleAnswerFormatProvider`.
New classes: `ORKVerticalScaleAnswerFormat` and `ORKContinuousVerticalScaleAnswerFormat`. The corresponding example steps have been added to `ORKCatalog`'s *Scale Question*.
> Add vertical scale answer format

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Consent/ORKConsentSceneViewController.m
- ResearchKit/Consent/ORKConsentSceneViewController_Internal.h
- ResearchKit/Consent/ORKVisualConsentStepViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
Stab at doing [Issue #68](https://github.com/ResearchKit/ResearchKit/issues/68).
Adds `ORKConsentSceneViewController_Internal.h` file with convenience methods to enable/disable scrolling, scroll to top, and set the `scrollView` `delegate`.
Modifies `ORKVisualConsentStepViewController` so:
- `ORKConsentSceneViewController` scrolling is enabled only after overlay animation completes (`updatePageIndex` method)
- Current `ORKConsentSceneViewController` scrolls to top in animated fashion before transitioning to next page
- Makes sure next `ORKConsentSceneViewController` is always scrolled to top (guards against going forward, scrolling downward, going back, and going forward again)
- Disregards scrolling when going back
I made the sample *lorem ipsilum* text in `ORKCatalog`'s *Consent task* …
> Add scroll to visual content screens

- docs/Survey/CreatingSurveys-template.markdown
* firstResult is a property of the ORKStepResult
* Remove extraneous space from the if statement
> Tweak code sample

- ResearchKit/ActiveTasks/HKSample+ORKJSONDictionary.m
- ResearchKit/ActiveTasks/ORKActiveStepViewController.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStepViewController.m
- ResearchKit/ActiveTasks/ORKTappingIntervalStepViewController.m
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKCompletionStepViewController.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKStepViewController.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Consent/ORKConsentSceneViewController.m
- Testing/ORKTest/ORKTest/DynamicTask.m
I have removed some seemingly unnecessary casts (and added an assert for an indirect assumption-based `NSDictionary` -> `NSMutableDictionary` cast). Removing these produces no warnings (nor static analyzer warnings), and all tests continue to pass.
If these were intentional, feel free to just close this pull request instead.
> Remove unnecessary casts

- docs/ActiveTasks/ActiveTasks-template.markdown
> Fix typo in ActiveTasks template

- ResearchKit/Common/ORKTaskViewController.m
Adjust internal `shouldPresentStep:` method not to call the delegate
on a nil step, and to return NO if the step is nil. When the task has
completed, a nil step indicates this, so handle that case explicitly
rather than depending on a semantically odd `YES` from `shouldPresentStep:`.
Testing: verified correct behavior for forward and backward navigation at beginning and end of tasks in `ORKTest` in simulator.
> Issue #122: `shouldPresentStep:` method should correctly handle nil step

- ResearchKit/ActiveTasks/ORKActiveStepQuantityView.m
- ResearchKit/ActiveTasks/ORKFitnessContentView.m
- ResearchKit/Common/ORKTaskViewController.m
This fixes a regression in quantity pair layout. The left view of
the quantity pair, the distance view, formerly always contained
content, which fixed the vertical height of the view. At some point
that content was no longer set, handling the no-pedometer-distance
case. The primary fix here is to ensure that a title and zero
quantity are present in the distance view, even if distance is
not available (as in the simulator).
Secondary fixes fix constraints to make them static, since they
do not need to be dynamically updated. We also introduce new baseline
constraints to better enforce alignment between the left and right
views.
Tested distance-only, heart-rate-only, both, and neither visible on
iPhone 6 on iOS 8.3. Tested with and without a value for heart rate,
with both visible. …
> Issue #118: Adjust fitness quantity pair layout

- samples/ORKCatalog/ORKCatalog/Base.lproj/LaunchScreen.xib
- samples/ORKCatalog/ORKCatalog/Base.lproj/Main.storyboard
I fixed *ORKCatalog*'s `LaunchScreen.xib` so it matches the main view controller.
I just added a height constraint of `64` to the navigation bar, and pinned the top of the table to it (so the separator vertical positions are in sync with the live view controller content inset). Tell me if you think there's a better approach instead.
> LaunchScreen: fix nav bar height and table view content inset

- ResearchKit/Common/ORKObserver.h
Very small cleanup. That line slipped when I extracted `ORKObserver` to its own file.
> Remove unneeded @class forward declaration in ORKObserver

- ResearchKit/Consent/ORKSignatureView.m
Fixes [issue #119](https://github.com/ResearchKit/ResearchKit/issues/119) by prioritizing the signature recognizer over the scrollview one. You can still scroll by dragging outside the signature area.
> Fix unable to draw signature when scrolling is enabled

- ResearchKit/ActiveTasks/ORKTappingContentView.m
Implementation of enhancement #148.
* On iPad, added more space between title, progress bar, and tap count.  Refactored code should allow more space to be easily added in-between if desired.
* Added `LAYOUT_DEBUG` colors to aid in layout debugging (per observed convention)
**iPad Screenshot (Portrait)**
**iPad Screenshot (Landscape)**
> Fix for Issue #148 - [iPad] Two finger tapping task vertical spacing improvement 

- ResearchKit/ActiveTasks/ORKAudioStep.h
- ResearchKit/ActiveTasks/ORKAudioStep.m
- ResearchKit/ActiveTasks/ORKAudioStepViewController.m
- ResearchKit/ActiveTasks/ORKFitnessStep.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStep.m
- ResearchKit/ActiveTasks/ORKTappingIntervalStep.m
- ResearchKit/ActiveTasks/ORKWalkingTaskStep.m
- ResearchKit/Common/ORKCountdownLabel.m
- ResearchKit/Common/ORKOrderedTask.m
- ResearchKit/Common/ORKStepViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- An `ORKCountdownLabel` fix which caused the `ORKActiveStepTimerView` to always show 0 as the starting value.
- A small `ORKActiveStep` subclass code homogenization.
- Fix some erroneous init methods missing the `[super init]` success check.
> ActiveStep fixes

- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKStepHeaderView.m
- ResearchKit/Common/ORKVerticalContainerView.m
Mini pull request: cherry-picked this from the `navigationrules` branch to avoid future conflicts. I plan to define new keys in the constraint refactor.
---
By the way the `_UppercaseConstraintKey` static string names in `ORKStepHeaderView.m` and `ORKVerticalContainerView.m` look a little weird. The `_` prefix feels like it should only be used for *ivar* names. Should we come up with a better naming convention for those?
How about this:
`_IllustrationToCaptionBaselineKey` -> `ORKStepHeaderViewIllustrationToCaptionBaselineKey`,
`_TopToIllustrationConstraintKey` -> `ORKVerticalContainerViewTopToIllustrationConstraintKey `,
etc.
> Extract ORKDefineStringKey() (was 'DEF_KEY()') to helpers

- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKScaleSlider.m
Fixes [issue #135](https://github.com/ResearchKit/ResearchKit/issues/135)
When you skip the step, the default value is hidden. Default value doesn't reappear when you go back twice, and go forward again.
I have also fixed a small visual glitch (occurring in stable as well): when you skip a step, the current value was hidden before the step transition. I guess we don't need to update the view just before an outgoing transition: the cell will be fine and empty if the user ever comes back.
> Fix ORKQuestionStepViewController losing its default value when going back

- ResearchKit/Consent/ORKConsentLearnMoreViewController.m
- ResearchKit/Consent/ORKConsentReviewController.m
[Pull request #166](https://github.com/ResearchKit/ResearchKit/pull/166) moved the margins from the mobile HTML document to the consent review view. This change broke "Learn More" margins.
This PR fixes that, and enables `bounces` in the consent review webview for homogeneity.
Also, tested after applying changes in [PR #168](https://github.com/ResearchKit/ResearchKit/pull/168): it looks ok as well.
> Fix margins in "Learn More" modal view

- ResearchKit/Consent/ORKSignatureView.m
Add a small circle to the current signature path in touchesBegan to
properly support dots in the signature view. This provides a nicer
experience to users, allowing them to dot their i's.
> Allow users to add a dot to the signature view

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
This adds a numberFormatter property to ORKScaleAnswerFormat and ORKContinuousAnswerFormat. Our motivation for this is to enable a continuous slider that displays a percentage, though it could be used for currency or other number formats.
Because this property is optional and likely to be used infrequently, I did not add it to the initializers.
This PR also includes a small change to ORKCatalog to display the second step for Scale Question as a continuous percentage, so you can view the appearance there.
> Add optional NSNumberFormatter to scale & continuous scale

- ResearchKit/ActiveTasks/ORKToneAudiometryContentView.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKResult.h
Fixes [Issue #183](https://github.com/ResearchKit/ResearchKit/issues/183).
Needs [pull request #187](https://github.com/ResearchKit/ResearchKit/pull/187) as a pre-requisite.
> Fix double bottom separator in boolean and text choice questions

- Testing/ORKTest/ORKTest/MainViewController.m
I missed one additional merge conflict which caused `ORKTest` not to compiler. Sorry.
> ORKTest: Fix remaining scale merge conflict

- ResearchKit/Consent/ORKSignatureView.m
This commit fixes a couple of issues with extra touches in the signature
view:
* Adding a second touch while signing would cause the path to jump to
the second touch, which is probably not what the user wanted.
* Once two touches were applied to the signature view, if both touches
ended simultaneously, gestureTouchesEnded: would return before calling
signatureViewDidEditImage: on the delegate. This could get the UI into
an odd state where there is a signature in the view but no clear
button below the view.
By ignoring the extra touches completely, we can also clean up the code
a little and remove the extra touches checks in the various touch event
handlers.
> Fix various multitouch issues in ORKSignatureView

- ResearchKit/Consent/ORKConsentDocument.m
Changes to ConsentDocument.m to fix bug outlined in issue 196, _signaturePageContent not being copied when the consent document is copied.
> _signaturePageContent not copied (fix for issue 196)

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Consent/ORKConsentDocument.h
- ResearchKit/Consent/ORKConsentDocument.m
- ResearchKit/Consent/ORKConsentDocument_Internal.h
- ResearchKit/Consent/ORKConsentSectionFormatter.h
- ResearchKit/Consent/ORKConsentSectionFormatter.m
- ResearchKit/Consent/ORKConsentSignatureFormatter.h
- ResearchKit/Consent/ORKConsentSignatureFormatter.m
- ResearchKitTests/ORKConsentDocumentTests.m
- ResearchKitTests/ORKConsentSectionFormatterTests.m
- ResearchKitTests/ORKConsentSignatureFormatterTests.m
This PR adds test coverage for `ORKConsentDocument`. To do so required a multi-stage process, as reflected in the commits:
1) Add an initializer to `ORKConsentDocument` to allow for dependency injection, as it depends on `ORKPDFHTMLWriter`. `-init` now calls through to this initializer, injecting default objects for the dependencies.
2) Write tests to cover `-makePDFWithCompletionHandler`. In the process of writing these tests, it became apparent that it would be beneficial to use formatter objects for `ORKConsentSection` and `ORKConsentSignature`, so those formatter classes were extracted.
3) Write tests to cover the formatters mentioned above.
As this process added three tests classes to the cover consent behavior, a Consent group was added under the ResearchKitTests group to hold …
> Tests for ORKConsentDocument

- ResearchKit/Common/ORKFormStep.m
- Testing/ORKTest/ORKTest/MainViewController.m
1) Form items can have no identifier if they are just placeholders
for section headers in the table view. We should ignore the nil
identifiers for the purpose of the uniqueness check.
2) In ORKTest, the scale questions task had a non-unique step
identifier in it.
> Fix identifier uniqueness issues

- Testing/ORKTest/ORKTest/MainViewController.m
The ORKTest copy is not part of the framework, not particularly
user visible, but it's nice to keep it consistent.
> Minor changes to copy in ORKTest

- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Consent/ORKConsentSharingStepViewController.m
- Clip question step tableview to bounds to avoid visible artifact on
consent sharing step.
- Make consent sharing step present its "learn more" content in a form sheet.
> Minor iPad layout fixes

- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKScaleSlider.h
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKScaleSliderView.h
- ResearchKit/Common/ORKScaleSliderView.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
Fixes [Issue #202](https://github.com/ResearchKit/ResearchKit/issues/202).
Also simplifies vertical scale autolayout code: I have replaced the `ORKScreenMetricVerticalScaleHorizontalMargin` metric (which was an indirect way of calculating the vertical scale height to avoid scrolling on *iPhone 5s* and up) with the simpler `ORKScreenMetricVerticalScaleHeight`. This avoids the use of the two layered delegate to obtain the scale height.
> Fix autolayout warnings after rotation on form with vertical scales

- ResearchKit.xcodeproj/project.pbxproj
- docs/InformedConsent/InformedConsent-template.markdown
- docs/Survey/CreatingSurveys-template.markdown
I have submitted an [*appledoc* pull request](https://github.com/tomaz/appledoc/pull/535) which allows us to fix the spurious cross reference warnings in the sample code blocks within the overview markdown documents.
This *ResearchKit* pull request makes the sample code in the markdown overviews *fenced code blocks* (these don't interfere with the current appledoc version either), and removes the *echo warnings* in the docs building script.
If you update to *appledoc v2.2.1 (build 1334)* (find it in the above PR) and merge this, the warnings when building the documentation will be gone.
> Fix overviews' example code warnings by using fenced code blocks

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeContentView.h
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeContentView.m
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeStep.h
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeStep.m
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeStimulusView.h
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeStimulusView.m
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeViewController.m
- ResearchKit/Common/ORKOrderedTask.m
- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKResult.m
- ResearchKit/Consent/ORKEAGLMoviePlayerView.m
- ResearchKitTests/ORKStepTests.m
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
This spun off while I was refactoring the constraints code. I'm submitting it as a separate PR because it fixes an erroneous `ORKDeviceMotionReactionTimeStep`'s *copy* method. 
Also:
- Refactors and simplifies constraint code.
- Conforms to whitespace conventions.
- Replaces `true`/`false` usage by `YES`/`NO`.
- Uses `SystemSoundID` instead of `UInt32`.
> Device motion reaction time code improvements

- ResearchKit/ActiveTasks/ORKActiveStepViewController_Internal.h
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeContentView.m
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeStimulusView.m
- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeViewController.m
- samples/ORKCatalog/ORKCatalog/ResultTableViewProviders.swift
This PR fixes three issues:
- *[Regression]* Failure animation was not showing if you shook the device before the blue dot appeared.
- Failure animation could be triggered a second time if you shook the device while the timeout failure animation was being shown.
- Reaction time result could cause a crash in `ORKCatalog` because the `timestamp` row was selectable.
> Reaction time task: fix issues

- ResearchKit/Common/ORKTaskViewController.m
Fixes #236. If something attempts to set the outputDirectory to nil, before presenting the task view controller, no exception should be thrown.
> Only attempt to create outputDirectory if it is non-nil

- ResearchKit/Common/ORKStepHeaderView.m
In certain scenarios, the interaction of auto layout and the selection of
the preferredMaxLayoutWidth could result in text being abnormally
truncated.
This fix lets the labels in the headerview be full width, by reducing the
content hugging priority.
This is slightly less efficient from a rendering perspective but makes
the autolayout calculation more stable.
> Fix unexpected text truncation

- ResearchKit/ActiveTasks/ORKVoiceEngine.m
Using a speech rate relative to the maximum speech rate is error
prone.
> Speech rate should use default speech rate

- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKTableContainerView.h
- ResearchKit/Common/ORKTableContainerView.m
Steps to reproduce:
- Build and deploy ORKTest to iPad sim
- Miniform -> Weight
- Tap on weight, Keyboard appears
- Tap on side of screen
Actual result:
- Keyboard does not hide
Expected result:
- Keyboard should hide.
Fix: allow parent view to specify a different tap off scope for the tap off
gesture recognizer by exposing a tapOffView property on ORKTableContainerView.
This has no API impact, since ORKTableContainerView is internal to the framework.
> Keyboard does not hide when tapping on margins on iPad

- ResearchKit/ActiveTasks/ORKDeviceMotionReactionTimeViewController.m
The reaction time task was untestable in the simulator. Here, we add
support for both timing out the task in the simulator, and for using the
shake gesture in the simulator.
> Reaction time task does not time out in sim

- ResearchKit/Common/ORKFormStepViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
If multiple section headers are requested, they will now all display.
As a side effect, this also fixes #245.
> Issue #245: enable multiple section headers

- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKResult.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
Adds a `consented` property to ORKConsentSignatureResult. This property
is true if the consent has been explicitly agreed by the user, and false
otherwise.
Added ORKESerializer support and verified unit tests pass.
> Add explicit consent review indication

- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKResult.m
- ResearchKit/Common/ORKStepViewController.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Consent/ORKConsentSection.m
- Testing/ORKTest/ORKTest/MainViewController.m
If the app is terminated while on an image capture step, and restarted
by build and run from Xcode, an exception would occur while restoring.
This is a symptom of serializing NSURL's directly, rather than serializing
either a relative path or bookmark data. This matters because the path can
change after a reinstall or restore from backup.
Here we make two changes. First, the output directory in task and step
view controller is serialized as bookmark data rather than directly as a URL.
Secondly, for results serialization, NSURL references are stored as paths
relative to the NSHomeDirectory (i.e. the root of the writable sandbox).
> Exception when saving and restoring image capture step.

- ResearchKit/Common/ORKFormItemCell.m
To avoid conflicts with system supplied UIView-Encapsulated-Layout-Height constraint.
> In FormItemCell, lower a heightConstraint's priority 

- ResearchKit/Common/ORKImageCaptureStep.m
- ResearchKit/Common/ORKImageCaptureStepViewController.m
- ResearchKit/Common/ORKImageCaptureView.h
- ResearchKit/Common/ORKImageCaptureView.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
This is a continuation of PR #263 taking into account @YuanZhu-apple 's PR #269.
Added support for optional to Image Capture Step.
Simplified the saving and using of continue and skip buttons.
Made the ORKCatalog use of Image Capture Step non-optional.
From PR #263:
Experiencing an error will now completely shut down the image capture step, including removing the continue and skip buttons, and resulting in only error text shown in the view.
> Image Capture Step optional support

- ResearchKit/ActiveTasks/ORKVoiceEngine.m
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKHelpers.m
Patch earlier this week adjusted the speech rate to use the default speech
rate. This is too fast a rate on iOS 8.3 and earlier.
> Fix speech rate on iOS 8.3 and earlier

- ResearchKit/Common/ORKHTMLPDFWriter.m
When useMetric is true, ORKHTMLPDFWriter is going to generate an extra
empty page before the signature page. Gaining little more pixels can
omit this extra empty page.
I also upload two output pdf files for quick references. The files are generated via ORKCatalog. Please note the page 3 of 4 is empty in A4 size while useMetric is true.
Example Consent.pdf in letter size
https://db.tt/EAHt9dMT
Example Consent.pdf in A4 size
https://db.tt/WV7LuDmS
> ORKHTMLPDFWriter generates an extra empty page when useMetric is true

- samples/ORKCatalog/ORKCatalog/ResultTableViewProviders.swift
Okay this one is finally a correct PR ;3
Fixes:
> Fix: Initializing from a metatype must reference 'init' explicitly

- ResearchKit/Common/ORKTaskViewController.h
- ResearchKit/Common/ORKTaskViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
Fixes the delegate not being set bug in `ORKTaskViewController` when initializing with `restorationData`.
> IOI # 325 - Delegate bug in ORKTaskViewController with restorationData

- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKStepNavigationRule.m
- Testing/ORKTest/ORKTest/MainViewController.m
A user was having trouble using `ORKPredicateStepNavigationRule` because she was passing an array of *steps* (instead of *step identifiers*) to the `destinationStepIdentifiers` argument. I added argument checking to make sure the objects in the arrays are of the correct class. Throws an exception if they aren't.
This PR also slightly rewrites `ORKTest`'s `ORKNavigableOrderedTask` example so it's easier to read.
> Enhance argument validation for Predicate Step Navigation Rule

- ResearchKit/ActiveTasks/ORKTouchRecorder.m
- ResearchKit/Common/ORKTaskViewController.h
Fixes two small typos (`deleagte` -> `delegate`).
> Fix small typos (deleagte -> delegate)

- ResearchKit/Common/ORKContinueButton.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
This reduces `ORKContinueButton`'s *height* from `44` to `32` points on the *compact vertical size class* on all *iPhone* devices except on the *iPhone 6 Plus* ([Issue #231](https://github.com/ResearchKit/ResearchKit/issues/231)).
This is the same behavior and metrics as `UINavigationBar`.
> Reduce continue button height on compact vertical size classes

- ResearchKit/Common/ORKAnswerFormat.m
**Fixed this bug for Decimal Number:**
1. Input: "20.000123"
2. Tap next, then go back
3. Then saved answer is 20 instead of 20.000123
> Fixed bug in ORKNumericAnswerFormat so the value shown is the full decimal

- ResearchKit/ActiveTasks/ORKTowerOfHanoiTowerView.m
- ResearchKit/Common/ORKResult.m
This fixes two small Tower of Hanoi issues:
- ORKTest serialization unit test was failing due improper `NSArray` unarchiving.
- The discs were not honoring the `tintColor` on first display ([Issue #349](https://github.com/ResearchKit/ResearchKit/issues/349)).
> Fix small Tower of Hanoi issues

- docs-standalone/coding-style-guide.md
This PR improves some of the *Coding Style Guide* examples to be more correct, more relevant or more interesting.
It also adds the *Constant Declarations* section which advises on how to declare constants (and discourages usage of the `kConstant` naming convention).
Finally, it updates the *Dot Syntax* section to reflect that now `array.count` and `string.length` are declared as properties instead of methods.
> Coding Style Guide improvements

- ResearchKit/ActiveTasks/ORKTowerOfHanoiTowerView.m
Caused by `[NSLayoutConstraint deactivateConstraints:_currentConstraints];`
> Fix a crash case in HanoiTowerView for iOS9

- Testing/ORKTest/ORKTest/MainViewController.m
This PR makes `ORKTest`'s *Navigable Ordered Task* example more complete by adding a form step and a predicate rule that matches both form step results.
> ORKTest: add form step to Navigable Ordered Task example

- ResearchKit/ActiveTasks/ORKFitnessContentView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/ActiveTasks/ORKToneAudiometryContentView.m
- ResearchKit/ActiveTasks/ORKWalkingTaskStepViewController.m
- ResearchKit/Common/ORKChoiceViewCell.m
- ResearchKit/Common/ORKContinueButton.m
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKHeadlineLabel.m
- ResearchKit/Common/ORKInstructionStepView.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
- ResearchKit/Common/ORKStepHeaderView.m
- ResearchKit/Common/ORKSubheadlineLabel.m
- ResearchKit/Common/ORKSurveyAnswerCell.m
- ResearchKit/Common/ORKTableContainerView.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Common/ORKVerticalContainerView_Internal.h
- ResearchKit/Consent/ORKConsentSignatureController.m
Fixed layout problem on iPad with iOS 9. (Tested in simulator)
Changes:
- Determine screen type from two dimensions: `vertical` and `horizontal`  
Renamed `ORKGetScreenTypeForWindow` to `ORKGetVerticalScreenTypeForWindow`
And introduced `ORKGetHorizontalScreenTypeForWindow`
Use horizontal screen type to determine a few metrics:
` ORKScreenMetricContinueButtonWidth`
`ORKScreenMetricHeadlineSideMargin`
`ORKScreenMetricLearnMoreButtonSideMargin`
~~`ORKScreenMetricTopToIllustration`~~
- Update `layoutMargin` in `ORKVerticalContainerView`'s `updateConstraintConstants`
> iOS9 iPad split view support

- ResearchKit/Common/ORKImageCaptureView.m
- ResearchKit/Localized/en.lproj/Localizable.strings
In iOS9 the image capture step does not function as intended when being used with split view. The `capture preview` freezes, but the `capture image` button is still visible. Tapping the `capture image` button causes the app to crash.
This fix removes the `capture image` button and the `capture preview` from the screen and displays a message for the user when in split view.
> iOS9: Split view fix for image capture step.

- ResearchKit/ActiveTasks/ORKTowerOfHanoiTowerView.m
- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
I figured an alternate fix for the *iOS 9* crash when you call `NSLayoutConstraint deactivateConstraints:` on constraints that reference removed views.
It adds the `void ORKRemoveConstraintsForRemovedViews(NSMutableArray *constraints, NSMutableArray *removedViews)` function to `ORKHelpers`. You have to call this whenever you remove subviews on a view that has a managed `_variableConstraints` mutable array.
Benefits of this fix:
- It allows to continue using the recommended `[NSLayoutConstraint deactivateConstraints:]`.
- It is easily compatible with my *constraint refactor* [pull request](https://github.com/ResearchKit/ResearchKit/pull/343), without having to switch back and forward between `[NSLayoutConstraint deactiveConstraints:]` and `[view removeConstraints:]`.
- When the bug is …
> Alternate fix for Tower of Hanoi iOS 9 constraint crash

- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKXAxisView.m
Fixed this:
```
for (NSInteger idx = 0; idx < self.numberOfXAxisPoints - ((NSArray *)_dataPoints[plotIndex]).count; idx++) {
[_dataPoints[plotIndex] addObject:dummyPoint];
}
```
Also Improved the code quality of `for loops` in charts code.
> Fixed a bug: updating array during a for loop cause incorrect behavior(cause crash)

- ResearchKit/Charts/ORKLineGraphChartView.m
`shouldDrawLinesForPlotIndex:` skips certain fillLayers with less than 2 valid data points. Crashed on line 149 `CAShapeLayer *fillLayer = _fillLayers[plotIndex];`.
- Use NSMutableDictionary (instead of a NSMutableArray) to store _fillLayers
- `plotIndex` is used as key in the dictionary
- Improved _fillLayers iteration
> Fixed a crash cause by omitted `fillLayer`

- ResearchKit/Common/ORKScaleSliderView.m
- Make slider's view bottom greater than slider's bottom, also greater than lower descriptionLabel's bottom.
- Make current value above slider's top, also above upper description Label's top.
> Convergence fix multiline desc on slider

- ResearchKit/ActiveTasks/ORKTowerOfHanoiStepViewController.m
Tower could be empty, so it is not safe to call `tower.disks[index];` without a check.
Accessibility announcement is only applicable when the both donor and recipient are valid.
> Fix NSRangeException in Hanoi Task

- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKTextFieldView.h
- ResearchKit/Common/ORKTextFieldView.m
Take _textFieldView's estimatedWidth into consideration when building the constraints for textFieldBasedformItemCell.
- implemented _textFieldView.estimatedWidth to return the larger value of text+unit and placeholder+unit
> Fix placeholder get truncated in FormItemCell.

- ResearchKit/Common/ORKChoiceViewCell.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- Make the checkmark always in the choiceCell, hide it when the cell is unselected.
So layout code get consistent bounds to calculate label's rect.
> Fix text label layout problem in right-to-left UI.

- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/ActiveTasks/ORKToneAudiometryContentView.m
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Common/ORKCustomStepView.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
- ResearchKit/Common/ORKTableViewCell.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentSignatureController.m
- ResearchKit/Consent/ORKSignatureView.m
Fixes views not having wide iPad margins introduced on [PR #370] (https://github.com/ResearchKit/ResearchKit/pull/370).
Also fixes some views not updating their `layoutMargins` properly when going in and out of *Split View* mode.
> iPad: constraint and layoutMargin code fixes

- ResearchKit/Charts/ORKCenteredCollectionViewLayout.m
- ResearchKit/Charts/ORKDiscreteGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView_Internal.h
- ResearchKit/Charts/ORKLineGraphChartView.m
- ResearchKit/Charts/ORKPieChartLegendCell.m
- ResearchKit/Charts/ORKPieChartLegendView.m
- ResearchKit/Charts/ORKPieChartPieView.m
- ResearchKit/Charts/ORKPieChartTitleTextView.m
- ResearchKit/Charts/ORKPieChartView.m
- ResearchKit/Charts/ORKXAxisView.m
- ResearchKit/Charts/ORKYAxisView.m
Add *lightweight generics* to all array declarations in the *chart* files.
This allows to remove all the *array-accessing casts*. Also a few incorrect `CALayer *` to `CAShapeLayer *` casts were detected and fixed.
I have also removed the `dataPointAtPlotIndex:pointIndex:` method since it no longer provides any advantage over directly accessing the *generics-parametrized array*.
> Charts: add lightweight generics to all array declarations

- Testing/ORKTest/ORKTest/Base.lproj/LaunchScreen.xib
- Testing/ORKTest/ORKTest/Charts/Charts.storyboard
- Testing/ORKTest/ORKTest/MainViewController.m
I have reorganised the `ORKTest` buttons by using a `UICollectionView` with alphabetically ordered sections ([Issue #419](https://github.com/ResearchKit/ResearchKit/issues/419)).
Let me know if any alternate section layout is better for testing and I can update it.
> Use sectioned 'UICollectionView' for presenting buttons in 'ORKTest'

- ResearchKit/Common/ORKImageCaptureView.m
Added a fix for image capture step if entering the preview step while already in split view.
> Fix for starting image capture step in split view.

- ResearchKit/ActiveTasks/ORKAudioContentView.m
This issue happens on iPhone only.
Some how, it works after I removed the constraints in GraphView.
> Fixed the graph view and time label overlapping.

- ResearchKit/Common/ORKSurveyAnswerCell.m
- ResearchKit/Common/ORKTableViewCell.m
Fixes the separator inset in the *numeric* and *test* questions on *iPad*.
Before:
---
---
After:
---
---
> iPad: fix separator inset in 'numeric' and 'text' questions

- ResearchKit/Common/ORKQuestionStep.h
- ResearchKit/Common/ORKQuestionStep.m
The `text` attribute is often missed by developers.
> Add another convenient constructor for ORKQuestionStep

- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKXAxisView.m
- ResearchKit/Localized/en.lproj/Localizable.strings
This PR fixes a crash when `graphChartView:titleForXAxisAtPointIndex:` (which is an optional method) is not implemented. Unfortunately, this fix needs new localized strings.
> ORKGraphChartView: fix accessibility crash when 'graphChartView:titleForXAxisAtPointIndex:' is not implemented

- samples/ORKCatalog/ORKCatalog/Charts/ChartDataSources.swift
Sorry, I forgot to update `ORKCatalog` as well.
> Charts: update ORKCatalog to use new data source method (convergence)

- ResearchKit/Common/ORKFormStep.h
- ResearchKit/Common/ORKFormStep.m
- ResearchKit/Common/ORKFormStepViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
Implements `ORKFormItem`'s `optional` property ([Issue #421](https://github.com/ResearchKit/ResearchKit/issues/421)). Also adds corresponding `ORKCatalog` example.
Now the *Continue/Done* button of form steps, irregardless of them being optional, only enables if:
- At least one form item has an answer.
- All answered form items are valid.
- All the non-optional form items have answers.
The previous behaviour was that the *Continue/Done button* was enabled for *optional form steps* if at least one question was answered; and was enabled for *non-optional form step* if all answers were answered. I changed this behaviour for homogeneity between forms, and because the implemented *form step optionality* provides maximum flexibility.
The *Skip button* behaviour remains unchanged: show it for …
> ORKFormItem: implement 'optional' property

- ResearchKit/Common/ORKAnswerFormat.h
Fixes some *headerdoc* warnings due to mismatching argument names.
Also hard wraps documentation text at line 100.
> ORKAnswerFormat: fix headerdoc warnings

- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
To reproduce:
1. Run ORKTest
2. Select Consent
3. Navigate to consent review step
Somehow `updateViewConstraints` is not being called. Have to force it.
Also added  super call to `viewWillTransitionToSize`
> Fix `blank` consent html review page.

- Testing/ORKTest/ORKTest/MainViewController.m
This PR fixes the column width not being updated after rotation in `ORKTest` (issue originally reported in [PR #343](https://github.com/ResearchKit/ResearchKit/pull/343).
It also makes the scroll view to use 3 columns for view widths equal or greater than the *iPhone 6* in landscape mode (*667 points*).
> ORKTest: fix column width not being updated after rotation

- ResearchKit/ActiveTasks/ORKAudioContentView.m
For #482, fixed by removing a constraint.
> Fix audio task layout problem

- Testing/ORKTest/ORKTest/MainViewController.m
This PR sorts `ORKTest` items alphabetically and adds a *Passcode* section.
> ORKTest: add 'Passcode' section and sort items alphabetically

- ResearchKit/Common/ORKFormStepViewController.m
For issue #489
1. Created `ORKFormSectionHeaderView` to update it constraint when screen rotates.
2. Use `dequeueReusableHeaderFooterViewWithIdentifier:` to cache created header views.
3. Other code refactoring.
> Fixed the section header misalignment in form page.

- ResearchKit/Common/ORKPasscodeStepViewController.m
- ResearchKit/Common/ORKPasscodeStepViewController_Internal.h
- Fixed bug: Keyboard did not show up after Touch ID failure when Authenticating passcode.
- Fixed bug: Editing flow was also retrieving the useTouchID value from Keychain, when it should not.
- Minor keyboard logic refactor.
- Moved two properties from `ORKPasscodeStepViewController_Internal.h` file to the `ORKPasscodeStepViewController.m` file since they were no longer being used outside the scope of the source file.
> Passcode updates

- ResearchKit/Common/ORKDefines_Private.h
- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
Currently, ORKLocalizedString() returns the key as a string if a value is not found for that key.
> For example, if we are in the German language setting, then it will display "PASSCODE_PROMPT_MESSAGE".
This PR redirects ORKLocalizedString() to find the value for the key in U.S. English and return that instead. If there is no value in the U.S. English either, then it will just return the key.
> With this update, if we are in the German language setting, then it will display "Enter passcode", if there is no translation available in German.
Issue #495
> IOI # 495 - Localization fallback language

- Testing/ORKTest/ORKTest/MainViewController.m
Fix for #506 
ORKURLFromBookmarkData() fails to return a valid URL, when the resolving directory is not exist.
> If a task in ORKTest has been cancelled and saved, the output directory should be kept.

- Testing/ORKTest/ORKTest/MainViewController.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
Currently, Wait Task is under the wrong section for ORKTest.
I went ahead and moved it into the appropriate section.
In ORKCatalog, I moved the code around to keep it alphabetically consistent with the ORKCatalog formatting.
> Rearranging ORKTest and ORKCatalog for WaitTask.

- ResearchKit/Consent/ORKConsentReviewStepViewController.m
Fix for #516
Regression caused by #443 (ORKFormItem: implement 'optional' property).
> Fix Issue #516: Consent required name logic is invalid

- ResearchKit/ActiveTasks/ORKPSATStepViewController.m
- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKFormItemCell.h
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKScaleSliderView.h
- ResearchKit/Common/ORKScaleSliderView.m
- ResearchKit/Common/ORKStepViewController.m
- ResearchKit/Common/ORKSurveyAnswerCellForScale.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
- samples/ORKCatalog/ORKCatalog/Results/ResultTableViewProviders.swift
This patch is a fix for #511 "Continue button is disabled on scale with default values"
1. Change `ORKTextScaleAnswerFormat`'s result to `ORKChoiceQuestionResult`. Since `ORKTextChoice` was used to specify selections.
2. Refactor ORKScaleSliderView to work better with three types of scale related answer format.
3. Other minor fixes
@rsanchezsaez I saw your fix #514, but after reviewing the `ORKTextScaleAnswerFormat`'s implementation, I found there are some fundamental issues. I prepared this patch to fix them.
Traditionally this type of default answer relied on cell's self reporting, for example, `dataPicker`. This patch follows it. 
Let me know if you like this one better. Thanks!
> Refractor scale answer format

- Testing/ORKTest/ORKTest/Charts/ChartDataSources.swift
- Testing/ORKTest/ORKTest/Charts/ChartListViewController.swift
- Testing/ORKTest/ORKTest/Charts/Charts.storyboard
- Testing/ORKTest/ORKTest/MainViewController.m
This PR adds a `Test Charts Performance` item which is meant to be used to test `ORKLineGraphChartView` and `ORKDiscreteGraphChartView` rotation and drawing performance. It (uglily) draws graph charts with lots of points.
> ORKTest: add 'Test Charts Performance' item

- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKNavigableOrderedTask.h
- ResearchKit/Common/ORKNavigableOrderedTask.m
- ResearchKit/Common/ORKResult.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
This PR improves the situation described on [Issue #502](https://github.com/ResearchKit/ResearchKit/issues/502).
It removes the `ORKNavigableOrderedTask`'s `_stepIdentifierStack` ivar (used for backwards navigation) and uses the *managed task result* instead. The *managed task result* will only show results for the steps that have been previously visited, so it can be used to simulate the backwards navigation stack.
The `ORKTaskViewController`'s `_managedStepIdentifiers` ivar has been converted into an `NSMutableOrderedSet`. When an already visited step is shown (either by going back, or by following a loop in a navigable ordered task), all the managed step identifiers which come later than the step being shown are removed.
This commit also updates `ORKTest` by removing the *Save For …
> Use results for backwards navigation in 'ORKNavigableOrderedTask'

- ResearchKit/Common/ORKEligibilitySelectionView.m
Fixing issue where toggling the tint color doesn't update the eligibility cell properly.
Issue https://github.com/ResearchKit/ResearchKit/issues/549
> IOI # 549 - Eligibility Tint Color Fix

- ResearchKit/Common/ORKImageCaptureStep.m
- ResearchKit/Common/ORKImageCaptureStepViewController.m
The original implementation was implementing `requestedPermissions` on ORKImageCaptureStep which resulted in the delegate call `taskViewControllerDidFinish: withReason:` if camera permission was not granted. Removing that implementation and instead only requesting permission on the actual image step resolved part of the issue.
The second half of the bug was due to the fact that in the error handling of the camera permissions, the delegate callback `taskViewControllerDidFinish: withReason:` was being called also. This caused the image capture step to never appear on the screen and actually show the error message.
Removing both those factors allows the user to navigate through the steps and see the error messages so that they can resolve it by changing privacy in settings or by skipping the …
> IOI # 517 - Image capture no permissions bug

- samples/ORKCatalog/ORKCatalog/Results/ResultTableViewProviders.swift
Replaced the field "address" with "userInput" in the ORKCatalog project which was causing a build error.
> Fixed build error in ResultTableViewProviders.swift caused by an outdated property.

- ResearchKit/Common/ORKStep.h
- ResearchKit/Common/ORKStep.m
This will allow a developer to copy a private subclass of ORKStep with a new identifier.
For an example usage, see:
https://github.com/Sage-Bionetworks/AppCore/blob/master/APCAppCore/APCAppCore/Library/Categories/ORKOrderedTask%2BAPCHelper.m
```
ORKInstructionStep *instructionStep = [tappingInstructionStep copyWithIdentifier:
[NSString stringWithFormat:@"%@.%@", APCTapInstructionStepIdentifier, handIdentifier]];
ORKActiveStep *activeStep = [tappingStep copyWithIdentifier:
[NSString stringWithFormat:@"%@.%@", APCTapTappingStepIdentifier, handIdentifier]];
```
In this example, 'ORKTappingIntervalStep' is a private class within the ResearchKit SDK so it cannot be instantiated directly with a new identifier used to differentiate tapping with the left hand from the right hand for the case …
> Added method to create a copy of a step with a new identifier

- ResearchKit/Charts/ORKGraphChartView.m
Actually, probably this should go to `convergence`, since it's a safe but critical bugfix. Feel free to close the other PR.
Fixes [Issue #589](https://github.com/ResearchKit/ResearchKit/issues/589).
> [ORKGraphChartView] Fix wrong selector check on accessibility (convergence)

- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKPieChartView.h
- ResearchKit/Charts/ORKPieChartView.m
This PR fixes [Issue #600](https://github.com/ResearchKit/ResearchKit/issues/600), and also adds `reloadData` methods to both chart types.
> [Charts] Fix crash when displaying graph chart with no data source 

- ResearchKit/Common/ORKOrderedTask.h
- ResearchKit/Common/ORKOrderedTask.m
- Testing/ORKTest/ORKTest/MainViewController.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
This pull-request addresses two (related) problems with the Timed Walk Active Task:
- The “Assistive Device” form items are now non-optional. These questions are mandatory in the context of the MSFC score (Multiple Sclerosis Functional Composite measure).
- The “Assistive Device” form step itself is now optional, by adding a `includeAssistiveDeviceForm` Boolean parameter to the factory method. This Timed Walk activity can be useful outside of the MSFC measurement, but then you probably don’t need the “Assistive Device” form details, so we think it’s nice to let the developer choose if he wants to include it or not.
> Add includeAssistiveDeviceForm parameter to timed walk task

- samples/ORKSample/ORKSample/HealthDataStepViewController.swift
This PR allows *ORKSample*'s onboarding to be completed on the *Simulator* despite *HealthKit* not being available.
> [ORKSample] Allow onboarding to proceed on the Simulator despite HealthKit not being present

- ResearchKit/Charts/ORKGraphChartView.m
The "No Data" label continued to appear in ORKGraphChartView after data was loaded because of a reversed boolean check.
> ORKGraphChartView - Remove the "No Data" label when there is data

- ResearchKit/Common/ORKStepNavigationRule.h
Deals with [Issue #603](https://github.com/ResearchKit/ResearchKit/issues/603).
- Improve whitespace
- Specify that passing `ORKNullStepIdentifier` (instead of `nil`) ends the task for *direct* and *predicate step navigation rules*.
> [ORKStepNavigationRule] Improve documentation

- ResearchKit.xcodeproj/project.pbxproj
This PR addresses #610. I confirmed that reverting ORKWaitStepView.h to Project visibility resolves the current build issue.
Note that along with ORKWaitStepView.h, commit 8c86b8d also switched these headers from Project to Private visibility:
* ORKReviewStep_Internal.h
* ORKReviewStepViewController_Internal.h
* ORKReviewStepViewController.h
* ORKWaitStepViewController.h
I wasn't sure if it any of these other headers should be exposed, and they don't import other private headers and cause build errors, so I didn't revert them. However, you may want to consider reverting them if they shouldn't be exposed.
> Revert ORKWaitStepView.h to Project visibility

- ResearchKit/Common/ORKNavigableOrderedTask.h
- ResearchKit/Common/ORKNavigableOrderedTask.m
**This change enables a developer to opt into linear progress reporting as implemented on `ORKOrderedTask` by setting a boolean flag on `ORKNavigableOrderedTask`.**
Currently, an `ORKNavigableOrderedTask` does not report any progress through its steps, and there is no way short of subclassing or (gasp!) swizzling to enable it to do so.
This seems reasonable because:
* A navigable ordered task can not be assumed to have any logical, linear set of steps
* A developer could implement custom progress reporting by subclassing `ORKOrderedTask` and implementing her own rules for `stepAfterStep:`, etc...
However, after further investigation, it seems desirable to allow a developer to opt into the linear progress reporting of `ORKNavigableOrderedTask`'s super class, `ORKOrderedTask`.
It seems one …
> Allow user to opt-in to linear progress reporting on ORKNavigableOrderedTask

- ResearchKit/Common/ORKNavigableOrderedTask.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
This PR fixes `ORKNavigableOrderedTask`'s `shouldReportProgress` property being ignored by `NSSecureCoding` and `NSCopying`, and also fixes `ORKTest` *unit tests* which were also omitting this property.
> [ORKNavigableOrderedTask] Fix 'shouldReportProgress' being ignored by NSSecureCoding and NSCopying

- ResearchKit/Common/ORKScaleSliderView.m
There's plenty of space for this to fit comfortably, and it allows much more flexibility in defining answer choices.
> Allow 2 lines of text on vertical scale sliders

- ResearchKit/ActiveTasks/ORKCountdownStep.h
- ResearchKit/Common/ORKCompletionStep.h
- ResearchKit/Common/ORKInstructionStep.h
- ResearchKit/ResearchKit.h
- ResearchKit/ResearchKit_Private.h
This PR deals with [Issue #560](https://github.com/ResearchKit/ResearchKit/issues/560) by exposing the `ORKCountdownStep` and `ORKCompletionStep` classes on the public framework header.
> [Framework] Expose ORKCountdownStep and ORKCompletionStep publicly

- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKResult.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
This PR deals with [Issue #369](https://github.com/ResearchKit/ResearchKit/issues/369).
It adds the `enabledAssistiveTechnology` property to `ORKStepResult`. The property can have the following values:
- `UIAccessibilityNotificationVoiceOverIdentifier` if *Voice Over* was active
- `UIAccessibilityNotificationSwitchControlIdentifier` if *Switch Control* was active
Also made sure `ORKTest` *serialization unit tests* continue to pass.
> [ORKStepResult] Add 'enabledAssistiveTechnology' property

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKStepViewController.h
Two meta fixes for the .framework (a typo, and a missing header)
> Typo/case fix in #include

- ResearchKit/Common/ORKScaleSliderView.m
This allows longer text labels by setting constraints to allow the slider to move as far left as 25% the width of the view, and allows the text labels to expand to the edge of the view (less a `SideLabelMargin` margin width).
Before:
After:
> Improved flexibility for laying out a vertical ORKScaleSliderView.

- ResearchKit/Consent/ORKSignatureView.h
- ResearchKit/Consent/ORKSignatureView.m
Add property for setting the stroke width variation (default to 3pts).
If the device supports 3D touch, use the true pressure to determine
how thick the line should be at a given point.
If the device does not support 3D touch, use the speed of the stroke
to determine how thick the line should be at a given point.
Here are some example screenshots using 3D touch:
... and here are some examples **not** using 3D touch:
> Update ORKSignatureView to support pressure sensitive stroke widths.

- ResearchKit/Charts/ORKDiscreteGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView_Internal.h
- ResearchKit/Charts/ORKLineGraphChartView.m
- Testing/ORKTest/ORKTest/Charts/ChartDataSources.swift
Currently, all plots have a fill color of 60% of their plot color. `ORKGraphChartView:fillColorForPlotIndex:` could be used to allow a plot to not be filled.
> allow plot fill color of ORKLineGraphChartView to be set by the delegate

- ResearchKit/Common/ORKHelpers.h
The following constants were missing `extern` declarations in `ORKHelpers.h`:
* `ORKScrollToTopAnimationDuration`
* `ORKCGFloatInvalidValue`
Aside from being semantically incorrect, this also caused an issue with using ResearchKit as a dependency in a CocoaPod; see #679.
Also see this issue in the CocoaPods repo: https://github.com/CocoaPods/CocoaPods/issues/5304. Thanks to @neonichu for helping pin this one down quickly.
> Fix declaration of constants in ORKHelpers

- ResearchKit/Charts/ORKDiscreteGraphChartView.h
- ResearchKit/Charts/ORKDiscreteGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView_Internal.h
- ResearchKit/Charts/ORKLineGraphChartView.m
- ResearchKit/Charts/ORKPieChartView.h
- ResearchKit/Charts/ORKPieChartView.m
- ResearchKit/Charts/ORKPieChartView_Internal.h
Declare customization properties as `IBInspectable` for charts and graphs.
Also makes these views `IBDesignable`, effectively displaying them as placeholders with no data.
PS: We could go a step further, and provide a data source sample for Interface Builder. This could be confusing, as IB would display data seemingly out of nowhere; but also useful to configure the `IBInspectable` properties. Any thoughts on this?
> Make chart and graph IBInspectable/IBDesignable

- ResearchKit/Common/ORKTaskViewController.m
By using the ivar rather than the property method accessor, this will fail for implementations where the developer is overriding `-defaultResultSource` rather than setting it. Since override is an accepted pattern in both objc and swift, direct access of the ivar can result in unexpected behavior.
> Fix bug where the defaultResultSource is using ivar rather than public property accessor

- ResearchKit/Common/ORKNavigableOrderedTask.h
- ResearchKit/Common/ORKNavigableOrderedTask.m
- ResearchKit/Common/ORKStepNavigationRule.h
- ResearchKit/Common/ORKStepNavigationRule.m
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
This PR deals with [Issue #535](https://github.com/ResearchKit/ResearchKit/issues/535).
It introduces the `ORKSkipStepNavigationRule` (abstract) and `ORKPredicateSkipStepNavigationRule` (concrete) classes, and the appropriate `ORKNavigableOrderedTask` methods to insert, view and remove them. Also adds some example code to `ORKTest`'s *Navigable Loop Task* item. Includes *unit tests* for all the new functionality, and makes sure all serialization tests continue to pass. Everything is documented.
> [ORKNavigableOrderedTask] Implement skip navigation rules

- ResearchKit/Common/ORKResult.h
By default, these values are set on instantiation to `now`. Not allowing null values for these simplifies archiving of results for upload to a server that is expecting non-nil values.
> ORKResult start/end dates should not be nullable

- ResearchKit/Common/ORKOrderedTask.h
- ResearchKit/Common/ORKOrderedTask.m
Added method to return a mutated copy of ORKOrderedTask with the steps included in the given array.
This method is intended to allow for mutating an ordered task (or subclass) while retaining the original class and properties that may not be publicly exposed, but with a mutated set of steps. An example of where this might be useful is if before performing an `ORKPredefinedActiveTask`, the app needed to query the participant about medications, diet or sleep. The app would need to mutate the steps in order
to insert their own steps. While an ORKOrderedTask could then be created with the same identifier and the new steps, subclass information such rules on an `ORKNavigableOrderedTask` would be lost.
> Copy the properties of an ORKOrderedTask (or subclass) and mutate the steps.

- ResearchKit/ActiveTasks/ORKHealthQuantityTypeRecorder.m
This is a fix for https://github.com/ResearchKit/ResearchKit/issues/713
It can be safely pulled into ResearchKit *now* while still targeting iOS 8.
With Xcode 8 and iOS 10, the `init` method used in iOS 8 has been deleted. Future versions of the iOS 10 beta may include this or they may not. This implementation allows for reverse-compatibility to iOS 8 (for apps that require supporting that version) while using the newer `init` method introduced in iOS 9 for both iOS 9 and iOS 10.
> Fix ORKHealthQuantityTypeRecorder to allow for iOS 10 and iOS 8 support

- ResearchKit/Common/ORKTaskViewController.h
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
See PR https://github.com/ResearchKit/ResearchKit/pull/733 for conversation.
In this case, our governance team required a change to the design for mPower to be made available in Luxembourg. We had to rearrange the onboarding steps and add our own custom implementation to meet their consent requirements. The app was failing the onboarding process because we were looking for the wrong step (we were using stepViewControllerWillAppear in the original AppCore implementation). The `stepViewControllerWillDisappear` method allows us to know when the `ORKConsentReviewStep` has finished which is really what we are interested in knowing.
> Add delegate method to task view controller for step will disappear

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKFormStep.h
- ResearchKit/Common/ORKFormStep.m
- ResearchKit/Onboarding/ORKRegistrationStep.m
- ResearchKitTests/ORKAnswerFormatTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
This answer format is intended to be used with an `ORKFormStep` in order to confirm a previous formItem input. Example usage includes a password or participant identifier that is used to anonymously identify a study participant.
Note: I intentionally decided *against* exposing `ORKConfirmTextAnswerFormat` publicly. Because it requires referencing another form item, it is requires special-case handling in `ORKFormStepViewController`.
> Expose method for instantiating an answer format for confirmation of another field.

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/ActiveTasks/ORKAudioLevelNavigationRule.h
- ResearchKit/ActiveTasks/ORKAudioLevelNavigationRule.m
- ResearchKit/Charts/ORKBarGraphChartView.h
- ResearchKit/Common/ORKOrderedTask.h
- ResearchKit/Common/ORKOrderedTask.m
- ResearchKit/Common/ORKOrderedTask_Private.h
- ResearchKit/Common/ORKStepNavigationRule.h
- ResearchKit/Localized/en.lproj/ResearchKit.strings
- ResearchKit/ResearchKit_Private.h
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
During user feedback and via researcher analysis, we were finding that the ambient noise in a room where the participant was attempting to record their voice was too loud. We added a navigation rule to the task to check for ambient noise level and direct the participant to move to a quieter location if necessary.
> Added a optional ambient noise check to the voice task.

- ResearchKit/ActiveTasks/ORKAudioRecorder.m
save the current AVAudioSession category before starting voice recording and then restore afterward.
We discovered a bug where running a voice task followed by a walking task would cause the spoken instructions to use the incorrect speaker. This fix addresses that issue.
> Fix audio-prompts-coming-from-earpiece bug

- ResearchKit/Common/ORKTaskViewController.h
- ResearchKit/Common/ORKTaskViewController.m
Adding this `optional` delegate method removes the necessity to jump through a number of hoops and implement a custom button item (text and action) for the cancel button in `-stepViewControllerWillAppear:` delegate method.
> Added delegate method for discarding results without confirming cancel.

- ResearchKit/Common/ORKStep.h
- ResearchKit/Common/ORKStep.m
- ResearchKit/Common/ORKStepViewController.h
- ResearchKit/Common/ORKStepViewController_Internal.h
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKitTests/ORKStepTests.m
- Testing/ORKTest/ORKTest.xcodeproj/project.pbxproj
- Testing/ORKTest/ORKTest/DragonPokerStep.h
- Testing/ORKTest/ORKTest/DragonPokerStep.m
- Testing/ORKTest/ORKTest/MainViewController.m
`- (Class)stepViewControllerClass` is defined as an internal method and is not exposed in the public API. This implementation allows for subclasses of ORKStep to return a view controller that is appropriate to their design.
In response to the explanation given in https://github.com/ResearchKit/ResearchKit/pull/719 for closing that pull request: Overriding a method that is marked as internal is brittle (internal methods cannot be assumed to remain and are not marked as deprecated when they might go away with a future release). Additionally, doing so with a Swift implementation will fail when the app is archived.
> Allow steps to instantiate the view controller

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/ActiveTasks/ORKTappingContentView.h
- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/ActiveTasks/ORKTappingIntervalStep.m
- ResearchKit/ActiveTasks/ORKTappingIntervalStepViewController.m
- ResearchKit/Common/ORKOrderedTask.h
- ResearchKit/Common/ORKOrderedTask.m
- ResearchKit/Common/UIImage+ResearchKit.h
- ResearchKit/Common/UIImage+ResearchKit.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
This pull request replaces https://github.com/ResearchKit/ResearchKit/pull/717
This includes the following required changes as well as the updated module:
1. `ORKTappingContentView` will show the skip button if applicable.
2. Added category method for flipping a set of images.
`ORKCatalog` has been modified to include this module as an example (in addition to the original tapping test that does not differentiate between left and right hand).
With the mPower app, one of the things our researchers wished to know was which hand the user was using to perform the tapping activity. This module is in addition to the existing modules that may be used in other apps and will allow the developer to specify either hand or both.
> Add task module for measuring bilateral tapping speed 

- ResearchKit/Consent/ORKConsentReviewStepViewController.m
This was casting to ORKSignatureResult without first checking the class. Produced a warning but not an error because *currently* the assumption is valid.
> Fix cast warning introduced with ORKSignatureResult

- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
I need feedback on naming and metric sizing. I came across this when I noticed that the first ‘welcome’ consent page header was vertically centered and the ‘data gathering’ page header wasn’t. See the before and after screenshots.
Welcome:
Before:
After:
> Support for 12.9 inch iPad Pro

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKScaleSlider.h
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKScaleSliderView.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
For example, this can be used to show a scale from bad to good by setting.
> Displaying a color gradient above the scale slider

- ResearchKit/ActiveTasks/ORKFitnessContentView.m
in the "updateTimerLabel" function, the timerLabel was always hidden because the labelString was null. The labelString was null every time because the "formatter" object (an NSDateComponentsFormatter object) was null the whole time. This object was null because inside the "dispatch_once", we did not reference/edit the existing static "formatter" object outside of the dispatch_once, but rather, we instantiated a new NSDateComponentsFormatter object.
This seems to work for me. I tested on iOS 6 simulator. I am on iOS 9/Xcode 7.
Edit: This pull request is related to the issue I made a day ago: #785
> Fixing bug where timerLabel did not display in ORKFitnessStep

- ResearchKit/ActiveTasks/ORKFitnessContentView.m
In my last pull request (#788) that was merged, I forgot to delete the "*" symbol. This actually caused the build to fail. The build should work now. 
(I'm really sorry about this, should've checked it more carefully.)
> Erased asterisk/pointer from my last pull request

- ResearchKit/Common/ORKTaskViewController.m
Our QA team found an EXC_BAD_ACCESS crash on strongSelf of this block callback.  It is caused by quickly canceling a task while it is transitioning.
To fix it, I added a check if weakSelf is nil so that we can avoid the strong self bad access crash.
> bad_access_fix

- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKPieChartPieView.m
This fixes crashes https://github.com/ResearchKit/ResearchKit/issues/691 and https://github.com/ResearchKit/ResearchKit/issues/766:
- `ORKGraphChartView` was crashing if laid out before the `dataSource` was set. The fix makes `-numberOfPlotsInGraphChartView` non-optional, and makes it to return 0 plots by default.
- `ORKPieChartView` was crashing if its `dataSource` returned a `0` value for any segment. Now segments with a `0` value are supported. The corresponding item will be added to the *legend*, and the percentage label will read `0 %`.
Big thanks to @p2 for discovering and/or investigating both issues.
> [Charts] Fix crashes

- ResearchKit/ActiveTasks/ORKTappingIntervalStepViewController.m
- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKResult.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
This PR adds a duration to ORKTappingSample.
When user press the button and don't release finger before times up, then i measure `duration` when step is finished for last sample.
> Adding tap duration to Tapping Task Issue #561

- ResearchKit/ActiveTasks/ORKFitnessContentView.m
- ResearchKit/Common/ORKPasscodeStepViewController.m
- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKResult.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
This PR is regarding the change in functionality outlined in issue  #791 ORKPasscodeStepViewController should report in its delegate if Touch ID was used or not 
This change allows the delegate of the taskViewController to be informed upon passcode creation if the user has decided to use TouchID or not.
It can be viewed by implementing the taskViewController delegate call
```
//WARNING THIS IS SWIFT
func taskViewController(taskViewController: ORKTaskViewController, didChangeResult result: ORKTaskResult) {
```
and then checking the result by iterating through the results of ORKTaskResult like so..
```
func taskViewController(taskViewController: ORKTaskViewController, didChangeResult result: ORKTaskResult) {
if let stepResult = result.results?.first as? ORKStepResult, passcodeResult = …
```
> Feature/touch ID report results of if touchID was chosen in Passcode Setup

- ResearchKit.podspec
Looks like when the pod spec version was bumped backticks were used instead of single quotes.
> Fix typo in podspec version quoting characters.

- samples/ORKCatalog/ORKCatalog/Results/ResultTableViewProviders.swift
checks for results instead of assuming they are present.
closes #841
> fixes crash when tapping results on ORKCatalog

- ResearchKit/Common/ORKVerticalContainerView.m
Revert Pull Request #806 to fix errors identified in ResearchKit issue #824.
The change applied in #806 appears to be unnecessary with the latest changes applied to master (ead0650).
Should correct some issues found in #824, as well as #820, and retaining the corrections on master that were identified in #774.
> Revert ResearchKit PR #806

- ResearchKit/Common/ORKHealthSampleQueryOperation.m
- ResearchKit/Common/ORKMotionActivityQueryOperation.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKDataCollectionTests.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
Fixes `ORKLocation` serialization unit test which was causing a *bad memory access* crash due  to `CLCircularRegion` being initialized using `init` instead of `initWithCenter:radius:identifier:` ([Issue #857](https://github.com/ResearchKit/ResearchKit/issues/857)). I've also submitted this to *bug report* as *Radar #29156129*, because I feel that trying to initialize `CLCircularRegion` through `init` should assert, rather than creating an invalid object.
Also, fix some `ORKDataCollectionTests` typos. The `testDelegateRejectDelivery` data collection test is still failing, I didn't have the time to familiarize with the new `ORKDataCollection` classes and fix the test.
---
Perhaps you guys should add a *GitHub* PR hook so the serialization tests are run for each PR, that way we'd find these …
> [ORKESerialization] Fix ORKLocation unit tests

- ResearchKit/Common/ORKStepViewController.m
This is a non nil property and should not be set to a possibly nil value. Doing so can cause a crash in Swift 3.0 override of `-(ORKStepResult)result` because of a violated assumption.
> Always set a date for non-nil ORKResult startDate

- ResearchKit/ActiveTasks/ORKAudioStep.m
- ResearchKit/ActiveTasks/ORKAudioStepViewController.m
Start was getting called in viewDidAppear:, creating an audio file, and meanwhile the superclass viewDidAppear: had dispatched a block to main that then saw the recorder was started and called resume, creating another audio file, only one of which was included in the results, leaving the other which the caller didn't know about and wasn't aware needed to be deleted, using up storage space over time. The fix is to use the shouldStartTimerAutomatically flag to let the superclass viewDidAppear: start the recorder, rather than override that method in the audio step view controller to start it explicitly.
> Fix audio step duplicate file creation bug

- ResearchKit/Common/ORKResultPredicate.h
Clarify comment on `+ predicateForConsentWithResultSelector:didConsent:` usage to avoid issues like https://github.com/ResearchKit/ResearchKit/issues/878.
> [ORKResultPredicate] Clarify comment on '+ predicateForConsentWithRes…ultSelector:didConsent:' usage

- ResearchKit/Common/ORKCustomStepView.h
Fixes issue around 'symbol not found...' when subclassing ORKQuestionStepCellHolderView
See https://github.com/ResearchKit/ResearchKit/issues/812
@YuanZhu-apple 
Thanks!!!
> PR for fixing issue812. 

- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKTaskViewController.m
By request from another dev, this allows the developer to force checking the default source _before_ using the previous result. If an empty `ORKStepResult` is returned, then the previous result will be ignored.
> Allow optional check of default result source before using previous.

- ResearchKit/Common/ORKResult.m
- ResearchKit/Common/ORKResultPredicate.m
- ResearchKit/Common/ORKResult_Private.h
- ResearchKit/Common/ORKTaskViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
Previous to this commit, `ORKTaskViewController` only tracked the _last_ result, inserting that result into the returned array of results for each instance of the step result with that identifier. This commit fixes that bug so that an `ORKNavigableOrderedTask` with a looping navigation will return the unique result for each loop.
Repro Steps:
1. Run the "Navigation Loop Task" in ORKTest
2. Loop through the answers 
Expected:
The results will show a different value for steps with the same identifier that are in the loop.
Actual:
All steps are replaced with the last result.
> Fix navigation looping to return unique results for each step.

- ResearchKit/Charts/ORKBarGraphChartView.m
- ResearchKit/Charts/ORKDiscreteGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKGraphChartView_Internal.h
- ResearchKit/Charts/ORKLineGraphChartView.m
- ResearchKit/Charts/ORKPieChartView.m
- ResearchKit/Charts/ORKPieChartView_Internal.h
This PR provides some improvements to the *sample data sources* used by *Xcode* when composing chart views on *Interface Builder*.
- Fix [Issue #886](https://github.com/ResearchKit/ResearchKit/issues/886).
- Add sample `ORKIBBarGraphChartViewDataSource` for `ORKBarGraphChartView`.
- Improve sample data source encapsulation and code reuse (and rename sample data source classes so they have the same name stem as the corresponding views) .
- Improve whitespace to conform to coding guidelines.
> [Charts] IBDesignable improvements

- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKitTests/ORKAnswerFormatTests.m
`ORKTextAnswerFormat` is created with a case-insensitive regex handler. This fixes this issue so that RegEx patterns that require case-sensitivity will work correctly.
> Fix ORKTextAnswerFormat regex to be case sensitive.

- ResearchKit/Common/ORKSignatureView.m
- ResearchKit/Common/ORKSkin.m
This PR Increases the height of `ORKSignatureView` for all phone sizes (the height on iPad remains the same), and the distance from its signing line to the bottom (on all devices). This addresses [Issue #623](https://github.com/ResearchKit/ResearchKit/issues/623). Even though the developer fixed the issue locally and the issue was closed, I feel it's a nice usability improvement.
---
Before (iPhone 4s)
---
After (iPhone 4s)
---
Before (iPhone 7)
---
After (iPhone 7)
> [ORKSignatureView] Increase height and distance of signing line to bottom

- ResearchKit/Common/ORKSignatureStepViewController.m
- ResearchKit/Common/ORKSignatureView.m
- ResearchKit/Common/ORKSkin.m
Fixes not being able to start traces on the top part of the signature view ([Issue #674](https://github.com/ResearchKit/ResearchKit/issues/674)).
The problem was that the height of the `ORKSignatureView` was larger than the one of the containing `ORKSignatureWrapperView` (it was peeking out from the top), so the signing gesture recognizer was not being triggered if the initial touch began within the overextended part.
I removed the overextending part. As a result the layout is slightly different (and I also had to reduce the *iPhone 4* height by 10 pixels to avoid vertical scrolling), but I think this is more coherent from the functionality point of view. See screenshots below.
---
Another option would have been overriding `- (BOOL)pointInside:(CGPoint)point withEvent:(UIEvent *)event` to …
> [ORKSignatureStepViewController] Fix not being able to start traces on the top part of the signature view

- ResearchKit/Common/ORKResult.m
It appears this was most likely the result of a copy and paste error. IMHO tests should be created for this class to catch small bugs like this one.
> Fix ORKTimedWalkResult isEqual: and copyWithZone:

- ResearchKit/Common/ORKAnswerFormat.m
When using fraction digits, the value displayed by the UI is not the same as the one from the results. For example if `maximumFractionDigits` is `2`, the user slides the slider to, let's say, `7`, the UI shows `7` but the result is something near `7` but not `7` (i.e. `6.9884...`).
This becomes important when using _navigation rules_, if we create a navigation rule and provide a `7` in our `NSPredicate` it **will always be false**.
Doing this fixes the issue:
`@ ORKAnserFormat`
``` Objective-C
- (ORKQuestionResult *)resultWithIdentifier:(NSString *)identifier answer:(id)answer {
ORKQuestionResult *questionResult = [[[self questionResultClass] alloc] initWithIdentifier:identifier];
// mirlhaq --- ContinuousScale navigation rules always evaluate to false because the result is different from …
```
> Fixes #834. "Continuous Scale Step - UI value and result value mismatch when using fraction digits."

- ResearchKit/Common/ORKPasscodeStep.h
- ResearchKit/Common/ORKPasscodeStep.m
- ResearchKit/Common/ORKPasscodeStepViewController.h
- ResearchKit/Common/ORKPasscodeStepViewController.m
- ResearchKit/Common/ORKPasscodeStepViewController_Internal.h
- ResearchKit/Common/ORKPasscodeViewController.m
Unless I'm mistaken, currently the only way to ask the user for a passcode is to use the static `ORKPasscodeViewController.passcodeAuthenticationViewController()` method, which produces a view controller to be modally presented with little in the way of customization or integration with other steps.
One use case we have is the need to show passcode authentication as a step along with an `ORKLoginStep` so that the user can switch between the two as desired.
This PR publicly exposes the `passcodeFlow` property and associated enums at the ORKPasscodeStep level so that its value can be set to `.authenticate` when constructing the step. The constructor that takes only an identifier remains untouched so existing code is not affected.
> Expose passcode flow types

- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStepViewController.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
We are including this copyright in mPower elsewhere in the app, but since this is a part of ResearchKit, the copyright should be shown as a part of the activity.
> There is a copyright that should be included with the memory game.

- ResearchKit/Common/ORKPasscodeStepViewController.m
When user is prompted to use Touch ID and they tap 'cancel', the number pad keyboard is shown (via call to becomeFirstResponder). But, the keyboard is invisible. It is there and not hidden because the user can still tap the keys, but cannot see them. Something inexplicable is happening when switching from Touch ID context back to app context. Calling becomeFirstResponder with dispatch to main queue after delay fixes this.
> Call becomeFirstResponder with dispatch to main queue after delay

- ResearchKit/ActiveTasks/ORKAudioLevelNavigationRule.h
- ResearchKit/ActiveTasks/ORKAudioLevelNavigationRule.m
- ResearchKit/Common/ORKStepNavigationRule.h
- ResearchKit/Common/ORKStepNavigationRule.m
- ResearchKit/Common/ORKStepNavigationRule_Internal.h
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
This will still throw an exception if the developer attempts to initialize an instance of the base class without inheriting it but allows developers to create navigation rules that inherit directly from the base class which are *not* included in the ResearchKit framework.
> Allow interhitance of navigation rules outside ResearchKit

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
In some contexts, it makes more sense to present users with customized "Yes" and "No" options (e.g., "Agree" vs. "Disagree", "I have" vs. "I have not", etc.) in Boolean tasks.
> Add custom yes and no strings option for ORKBooleanAnswerFormat

- ResearchKit/Common/ORKPasscodeStep.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
When this was pushed to master, the `ORKTest` tests weren't run on our fork because we have added tests to check equality for primitive values. This fixes the tests.
> Fix missing passcodeFlow serialization, copying, encoding and equality

- ResearchKit/ActiveTasks/ORKActiveStepViewController.m
- ResearchKit/ActiveTasks/ORKFitnessContentView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStepViewController.m
- ResearchKit/ActiveTasks/ORKTowerOfHanoiStepViewController.m
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKCompletionStepViewController.m
- ResearchKit/Common/ORKOrderedTask.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Consent/ORKConsentSharingStep.m
When using string formatting, Apple’s recommendation is to use `localizedStringWithFormat:` for cases where the string may be displayed in a language that reads from left-to-right.
> Fix localization for formatted strings so that they will localize correctly left-to-right.

- ResearchKit/ActiveTasks/ORKShoulderRangeOfMotionStep.h
- ResearchKit/Common/ORKVideoInstructionStep.h
It seems like issue #649 has started to appear again. This fixes it by changing the class-visibility for two new steps that have been added since the last fix was merged.
> Fix class visibility for new types of Steps, fixes #649

- ResearchKit/Common/ORKPasscodeStepViewController.m
This is a fix for issue #960, `-viewDidAppear:` is called but the view isn't on screen yet when the view controller is set in a `UIPageViewController`. Might be a bug from UIKit? https://forums.developer.apple.com/thread/15441
> [ORKPasscodeStepViewController] Make sure the view has been laid out before showing the keyboard

- ResearchKit/Common/ORKPasscodeStepViewController.m
in ORKPasscodeStepViewController, supported interface orientation is
set to UIInterfaceOrientationMaskPortrait. To support any orientation
this was changed to UIInterfaceOrientationMaskAll.
> Issue #973

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
Our application requires a business rule where user input can be restricted to a specific decimal scale (number of digits right of the decimal point) for the `ORKNumericAnswerFormat`. The code change adds a `scale` property to `ORKNumericAnswerFormat` and when not `nil` will restrict entering of decimal values beyond the specified scale value.
> Added decimal scale limit to `ORKNumericAnswerFormat`

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKChoiceAnswerFormatHelper.h
- ResearchKit/Common/ORKChoiceAnswerFormatHelper.m
- ResearchKit/Common/ORKImageSelectionView.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
This allows the image choices of the ORKImageChoiceAnswerFormat to be vertically laid out.
This is one example of a possible use case.
Sample leg image credit to [Ivan Boyko](https://www.iconfinder.com/visualpharm).
> Added vertical layout option and multiple choice to ORKImageChoiceAnswerFormat

- samples/ORKCatalog/ORKCatalog/Supporting Files/Info.plist
Adds the necessary Info.plist keys for requesting access to camera and microphone, as required in the Image Capture Step and Video Capture Step from ORKCatalog.app
> Add Info.plist keys for microphone and camera access

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKitTests/ORKRecorderTests.m
- Testing/ORKTest/ORKTestTests/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
This PR fixes three separate unit test failures:
- Localization recorder failure. The `ork_doubleEqual()` method had too high of a precision, and failed for the *latitude* double floating point rounding errors when boxing and unboxing into `NSNumber`. Original value:  *37.3131699999999995043*, compared value: *37.313169999999978188*, difference: *2.13162820728030055761e-14*, minimumDifference: *1.65703761823010543768e-14*. I increased the K value (units of errors in the last place) from *1* to *2*.
- `ORKESerializationTests` failure due to not handling the new `scale` property of `ORKNumericAnswerFormat`. I took the chance to rename `scale` to `maximumFractionDigits` which is coherent with the `NSNumberFormatter` property.
- `ORKESerializationTests` failure due to not handling the new …
> [Misc] Fix unit tests

- README.md
The `HelloResearchWorld` Swift code example from the README isn't up-to-date with latest Swift syntax and does not compile with Swift 3.x.
> Update README.md Swift example code to latest Swift syntax

- ResearchKit/Common/ORKFormStepViewController.m
- Testing/ORKTest/ORKTest/Tasks/TaskFactory+Forms.m
When the user taps the Skip button on a form step, ORKFormStepViewController [sets a private `_skipped` field to `YES`](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKFormStepViewController.m#L739). It [checks the value](https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKFormStepViewController.m#L702) of `_skipped` whenever it needs to produce an ORKStepResult.
This can cause the form step to get into a bad state in the following scenario:
1. User taps Skip
2. Forward navigation is prevented, for example by an `ORKTaskViewControllerDelegate` instance implementing `taskViewController:shouldPresentStep:` and returning `NO`
At this point, the user is still viewing the current form step, but `_skipped` is still true. Thus, all of the …
> Fix for ORKFormStepViewController getting stuck in a "skipped" state

- ResearchKit/Consent/ORKConsentDocument.m
Fixes #992. "Consent PDF with htmlReviewContent doesn't add signature page.
The original (unresolved and closed by lack of activity) issue is #992 .
I checked the issue and also this change works.
> Fixes #992. "Consent PDF with htmlReviewContent doesn't add signature page

- ResearchKit/Localized/en.lproj/ResearchKit.strings
- ResearchKit/Onboarding/ORKRegistrationStep.h
- ResearchKit/Onboarding/ORKRegistrationStep.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
Added phone number form item for ORKRegistrationStep.  Includes properties phoneNumberValidationRegularExpression and phoneNumberInvalidMessage.  Added localized strings in english for PHONE_NUMBER_FORM_ITEM_TITLE and PHONE_NUMBER_FORM_ITEM_PLACEHOLDER.  PHONE_NUMBER_FORM_ITEM_PLACEHOLDER defaults to +1 (555) 555 5555 unless developer sets place holder in the steps place holder.  Updated ORKCatalog.
> Added phone number form item for ORKRegistrationStep #1068

- ResearchKit/Consent/ORKConsentReviewController.m
This pull request fixes the issue reported by @mmertsock in #1019. The issue is related to UIToolbar layout in the consent review step on iPhone X.
> [ResearchKit] fix for issue #1019 - toolbar

- ResearchKit/Common/ORKPasscodeStepViewController.m
This patches the undesirable behavior that the ORKPasscodeTextField displays trailing, excessive digits if keystrokes are registered in quick succession.
> Suppress ORKPasscodeTextField input overflow

- ResearchKit/Common/ORKOrderedTask+ORKPredefinedActiveTask.h
- ResearchKit/Common/ORKOrderedTask+ORKPredefinedActiveTask.m
- ResearchKit/ORKDeprecated.h
- ResearchKit/ORKDeprecated.m
1) deprecate an initializer to avoid duplicate code paths
2) use ORKText choice for picker view instead of NSString which was causing a run time crash
> Timed walk task cleanup

- ResearchKit/ActiveTasks/ORKHealthClinicalTypeRecorder.h
- ResearchKit/ResearchKit_Private.h
When building project with iOS SDK lower than 12, it causes compilation error because `ORK_CLASS_AVAILABLE` was expecting class which in fact was omitted by `#if defined(__IPHONE_12_0)...`
It was breaking compilation mostly for CocoaPods, which reads all headers specified in .podspec file.
Additionally `ResearchKit_Private.h` was simplified because validation is done directly in `ORKHealthClinicalTypeRecorder.h` file.
Thanks for help to @alistra
> Fixed position of ORK_CLASS_AVAILABLE

- ResearchKit/Common/ORKPDFViewerStepView.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
Resolves rdar://problem/42255725. Tested on iPhone 8.
> Add accessibility labels to PDF Viewer action buttons.

- ResearchKit/Common/ORKCompletionStepViewController.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
The completion view looks like it's now just always a check in a blue
circle. Update the label to a fixed string. This avoids interpolating
nil, which was happening because captionLabel is not visible here (and
as such moving focus to it with a screen change is also inappropriate).
Resolves rdar://problem/42294298. Tested on iPhone 8.
> Use fixed accessibility label for the completion view.

- ResearchKit/ActiveTasks/ORKSpeechRecognitionContentView.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
Resolves rdar://problem/42294456. Tested on iPhone 7.
> Use UIAccessibilityTraitStartsMediaSession on the Start Recording button, so that VoiceOver doesn't speak the button title when you activate it.

- ResearchKit/ActiveTasks/ORKSpeechInNoiseContentView.m
Resolves rdar://problem/42294815. Tested on iPhone 7.
> Use UIAccessibilityTraitStartsMediaSession on the Play Audio button, so that VoiceOver doesn't speak the button title when you activate it.

- ResearchKit/Common/ORKAnswerTextView.m
- ResearchKit/Common/ORKCustomStepView.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
- Expose only one element for the text view.
- Expose a custom action to allow dismissing the keyboard.
Resolves rdar://problem/42294608. Tested on iPhone 7 with VoiceOver and Switch Control.
> Accessibility fixes for the transcript view in the Speech Recognition task.

- ResearchKit/ActiveTasks/ORKSpeechRecognitionContentView.m
- The phrase to be recorded now scales with dynamic type.
- The Start Recording button expands if needed to fill the available width.
> Improved Dynamic Type support for the Speech Recognition recording view.

- ResearchKit/Consent/ORKConsentReviewController.h
- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentReviewStep.h
- ResearchKit/Consent/ORKConsentReviewStep.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
This adds an additional property to `ORKConsentReviewStep` called `requresScrollToBottom`.  When set to true, the "Agree" button will not be activated until the user scrolls all the way to thee bottom of the content.  This is for a particular research project we are working with where it's very important that the participant fully read and understand the consent - and we figured it would make sense to contribute back to ResearchKit in case someone else could use the feature.
> Option to require scrolling to the bottom of ORKConsentReviewStep

- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/ActiveTasks/ORKTappingIntervalStepViewController.m
- ResearchKit/ActiveTasks/ORKToneAudiometryContentView.m
- ResearchKit/ActiveTasks/ORKToneAudiometryStepViewController.m
- ResearchKit/ActiveTasks/ORKTrailmakingContentView.m
- ResearchKit/ActiveTasks/ORKTrailmakingStepViewController.m
- ResearchKit/ActiveTasks/ORKdBHLToneAudiometryContentView.m
- ResearchKit/Common/ORKOrderedTask+ORKPredefinedActiveTask.m
- ResearchKit/Common/ORKRoundTappingButton.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
- In the tone audiometry test, the user has a chance to determine the location of the buttons during the practice step. Once the test begins, the buttons become directly tappable.
- In the two finger tapping interval test, the user can also determine the location of the buttons first. Then on the first activation of either button, the buttons become directly tappable, but the tap is not registered yet.
- In the dBHL tone audiometry test, the user is given instructions about the button and it is directly tappable.
- In the trailmaking test, the user is given instructions about the buttons and they are directly tappable.
> Improve usability of tests that use ORKRoundTappingButton.

- ResearchKit/ActiveTasks/ORKCountdownStepViewController.m
- ResearchKit/ActiveTasks/ORKTrailmakingContentView.m
- ResearchKit/ActiveTasks/ORKTrailmakingStepViewController.m
- Make sure the text doesn't grow outside the bubbles
- Make sure the "Starting text in" text doesn't get truncated
- Scale the timer and error text
> Improvements to Dynamic Type support in the Trail Making Test.

- samples/ORKSample/ORKSample/Info.plist
NSHealthShareUsageDescription must be longer than one word, otherwise HealthKit will throw a runtime exception during the on-boarding or profile view controller. This can cause a crash in the ORKSample app.
> NSHealthShareUsageDescription must be longer than one word

- ResearchKit/Common/ORKTaskViewController.h
- ResearchKit/Common/ORKTaskViewController.m
Setting an `ORKTaskViewController` to cancelable omits showing the "End Task" action sheet, and dismisses the view controller directly, which can improve the UX for non-data-collecting tasks that are not necessary to deal with user cancellation.
> Allow task view controller to be canceled directly

- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
passcodeTask identifier has to be ".passcodeTask" not ".passcodeStep".
> Fixing a typo/bug in TaskList.

- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
adds iPhone Max and iPhone XR (same points resolution)
> ScreenType iPhone Max & XR

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/ActiveTasks/ORKRangeOfMotionStep.m
- ResearchKit/ActiveTasks/ORKSpeechRecognitionStep.m
- ResearchKit/ActiveTasks/ORKToneAudiometryStep.m
- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKFormStep.m
- ResearchKit/Common/ORKQuestionStep.m
- ResearchKit/ResearchKit.h
- ResearchKit/ResearchKit_Private.h
- Testing/ORKTest/ORKTestTests/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
This PR addresses the majority of unit test failures mentioned in issue #1151 for ORKTest/ResearchKit.
- covers serialization for tone audiometry, PDF viewer, speech in noise, environmental SPL meter, speech recognition, and Amsler grid steps
- covers serialization for streaming audio recorder and clinical recorder configurations, numeric answer format
No new warnings. Down to a single failure - ORKNumericAnswerFormat is not serializing as JSON properly. I'd appreciate another set of eyes to figure that out though as I'm stumped at the moment.
> ORKTest unit tests fail

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
- ResearchKit/Onboarding/ORKLoginStep.m
- ResearchKit/Onboarding/ORKRegistrationStep.h
- ResearchKit/Onboarding/ORKRegistrationStep.m
- ResearchKitTests/ORKAnswerFormatTests.m
- Testing/ORKTest/ORKTest/Tasks/TaskFactory+Forms.m
- Testing/ORKTest/ORKTestTests/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
* Also adds support for the `passwordRules` property to support automatic secure passwords.
[`textContentType`](https://developer.apple.com/documentation/uikit/uitextcontenttype?language=objc), introduced in iOS 10, enables UITextFields to provide semantic hints to iOS so the keyboard can make more targeted selections. For instance, if you specify a `textContentType` of `UITextContentTypeGivenName` when the user focuses on the corresponding answer field, the keyboard will recommend the given name of the user from their iCloud profile. By properly annotating UITextFields, filling out a typical name and contact form becomes much easier to do, hopefully resulting in more completed surveys/forms/sign-ups/etc.
iOS 11 introduced functionality for [AutoFilling usernames and …
> Add support for textContentType from UITextInputTraits to ORKAnswerFormat

- CONTRIBUTING.md
This PR proposes a correction to the _ResearchKit Forum_ references in the contributing guidelines.
At present `CONTRIBUTING.md` refers questions and/or suggestions to `researchkit-dev`, which no longer appears to be a valid mailing list at `lists.apple.com`. 
These obsolete links are replaced with valid references to the _ResearchKit Forum_ used elsewhere in the project, including `README.md`.
> Correct link to ResearchKit forum in contributing guidelines

- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStepViewController.m
- samples/ORKParkinsonStudy/ORKParkinsonStudy.xcodeproj/project.pbxproj
- samples/ORKParkinsonStudy/ORKParkinsonStudy/Base.lproj/Localizable.strings
- samples/ORKParkinsonStudy/ORKParkinsonStudy/Onboarding/ConsentDocument.swift
- samples/ORKParkinsonStudy/ORKParkinsonStudy/Onboarding/OnboardingViewController.swift
- Fix broken “Disagree” button in example onboarding consent flow
- Delegate reference cycle
- Tidy up localized strings
- Remove unused language config
- Tidy signature access at end of onboarding
- Minor syntax tidy
> Minor example project onboarding cleanup

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKChoiceViewCell.h
- ResearchKit/Common/ORKChoiceViewCell.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKLabel.m
- ResearchKit/Common/ORKMultipleValuePicker.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKReviewStepViewController.m
- ResearchKit/Common/ORKScaleSliderView.m
- ResearchKit/Common/ORKTableViewCell.m
- ResearchKit/Common/ORKTextChoiceCellGroup.m
- ResearchKit/Common/ORKValuePicker.m
adding support for setting attributed string to the primary text label of ORKAnswerFormat
potential fix for #1223
> attributed text for surveys

- ResearchKit/Common/ORKAnswerFormat.m
Previous implementation could accidentally accept white space in email string
te st@mail.ex would be accepted because the substring "st@mail.ex" would be valid.
> Fixed email regex to enforce start and end of string.

- ResearchKit/Common/ORKFormStep.h
- ResearchKit/Common/ORKFormStep.m
- ResearchKit/Common/ORKFormStepViewController.m
Implements an enhancement [discussed here recently](https://github.com/ResearchKit/ResearchKit/pull/1264/files#diff-f953f90e65bcefc4e8aefb2a8a587851) where an `ORKFormItem` can be hidden via an `NSPredicate`. This can be useful for a showing/hiding later `ORKFormItem`s based on answers in the same `ORKFormStep`. This is demonstrated below. It can also be used to simply provide conditional display of various items in a lengthy `ORKFormStep` as well based on previous responses.
In this implementation, a `ORKFormItem` where `isOptional` is `false` will NOT be required to move to the next step. This prevents an unsatisfiable condition in validation where a required step is not visible to the user.
Furthermore, results for hidden form items at the time the step is completed are removed, …
> Conditionally Hide an ORKFormItem based on an NSPredicate

- ResearchKit/Common/ORKReviewStep.m
Bug introduced here:
commit 9ef1876c45f874ba04d67dd9c5ba7ae5d88a52c3
Author: Brian Ganninger <coder@infinitenexus.com>
Date:   Sun Nov 25 20:44:22 2018 -0800
[code cleanup] Review mismatched nil returns (issue #1214)
——
Impact:
Causes an embedded ORKReviewStep to return no steps
> Missing embedded summary in ORKReviewStep

- ResearchKit/Common/ORKFormStepViewController.m
Fixes #1310 - In certain cases with section headings, this would cause a zero to be used as an index for an `ORKTableSection` which is incorrect and would cause a failure in later processing for `_beginningIndexPath` inside the `ORKTextChoiceCellGroup`.
> Bugfix - Index needs to be _allSections

- ResearchKit.podspec
Updates the podspec so that ResearchKit (2.1.0-beta) is installable from a github reference again
> Fixes podspec in cocoapods 1.8.0

- ResearchKit/Common/ORKInstructionStepViewController.m
In the current version of the ORKLearnMoreStepViewController, the **Close** button is not showing up when presented from the ORKInstructionStepViewController. The solution is to wrap ORKLearnMoreStepViewController in UINavigationController, in the same manner as it is in ORKFormStepViewController: https://github.com/ResearchKit/ResearchKit/blob/master/ResearchKit/Common/ORKFormStepViewController.m#L1371-L1373
> Fix displaying of Close button in ORKLearnMoreStepViewController

- ResearchKit/Common/ORKNavigationContainerView.m
We used to retrieve the view's tint color from a reference to the window held by the AppDelegate, however, iOS 13 introduced a new SceneDelegate pattern in which there may be more than one window. We now have to retrieve the tint color from window that the view belongs to, as there may be multiple windows with different tint colors.
> Retrieve tint color from view's window instead of AppDelegate's window

- ResearchKit.xcodeproj/xcshareddata/xcschemes/ResearchKit.xcscheme
This is preventing carthage from building ResearchKit with:
```
carthage update ResearchKit --platform ios
```
`Cartfile` contains:
```
github "ResearchKit/ResearchKit" "master"
```
> remove tests from archive

- ResearchKit/Common/ORKStepContentView.m
Clip the image at the top of the step for cases when the aspect ratio pushes the image outside of the frame.
> Clip step image

- ResearchKit/Common/ORKKeychainWrapper.m
This PR updates a call to a deprecated method that generated warnings in projects that import ResearchKit
> Update deprecated method call

- ResearchKit/Common/ORKHelpers_Internal.h
Fixes a compiler warning about a method that returns an unexpected nil.
> Silence warning about nullable return types

- ResearchKit/Common/ORKSurveyAnswerCellForImageSelection.m
- ResearchKit/Common/ORKSurveyAnswerCellForLocation.m
- ResearchKit/Common/ORKSurveyAnswerCellForNumber.m
- ResearchKit/Common/ORKSurveyAnswerCellForSES.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
Use the `impliedAnswerFormat` for cells. Otherwise, the explicit conversion may fail since the original `answerFormat` is not an instance of the desired class type. Thus lead an exception.
For example, let us create an answer format:
```
let answerFormat = ORKHealthKitQuantityTypeAnswerFormat(quantityType: quantityType, unit: unit, style: .integer)
```
And create a task which encapsulates the format:
```
let step = ORKQuestionStep(identifier: "step0", title: title, question: text, answer: answerFormat)
let task = ORKOrderedTask(identifier: "task0", steps: [step])
```
When any cell (`ORKSurveyAnswerCellForNumber`) renders these task, it will assume the the answer format is `ORKNumericAnswerFormat`. And invoke `ORKNumericAnswerFormat` exclusive methods, lead to an exception. …
> Use implied answer format for cells

- ResearchKit/Common/ORKTaskViewController.m
When presenting this view, the navigation bar isn't being set, leaving a clear bar depending on how the ORK task is presented.
This fix simply sets the bar to color of the view so it's not clear.
> Set ORKTaskViewController nav background color

- ResearchKit/Common/ORKKeychainWrapper.h
- ResearchKit/Common/ORKKeychainWrapper.m
- ResearchKit/Common/ORKPasscodeStepViewController.m
- ResearchKit/Common/ORKPasscodeViewController.m
This PR updates `isPasscodeStoredInKeychain` in `ResearchKit/Common/ORKPasscodeViewController.m` to remove the `@throw NSException` called when the dictionary is `nil`, and instead just return `NO` here.
This prevents a crash when `isPasscodeStoredInKeychain` is called in certain circumstances, such as when called at the very first launch of the application.
---
It also updates the invocation of
```
(id<NSSecureCoding>)objectOfClass:(Class)objectClass forKey:(NSString *)key error:(NSError **)errorOut
```
to be
```
(id<NSSecureCoding>)objectsOfClasses:objectClasses forKey:(NSString *)key error:(NSError **)errorOut
```
\- thus taking an `NSSet<Class>` input and ensuring that `NSString` and `NSNumber` are included in the allowed classes set. This prevents warnings in the console, such as
``` …
```
> Prevent isPasscodeStoredInKeychain crash, correct warnings

- ResearchKit/Common/ORKCheckmarkView.m
- ResearchKit/Common/ORKChoiceViewCell.m
- ResearchKit/Common/ORKDontKnowButton.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKHelpers_Internal.h
- ResearchKit/Common/ORKNavigationContainerView.m
- ResearchKit/Common/ORKTaskViewController.m
When an app is using the SwiftUI lifecycle (App protocol) and doesn't use the scene delegate, the tintColor isn't properly inherited in surveyViewController in OCKSurveyTaskViewController from the calling view. This occurs with the latest commit on the main of CareKit and the latest commit on the main of ResearchKit (https://github.com/ResearchKit/ResearchKit/commit/a89059f5dc2a91f36785b184f914b5e5fdb05877)
More info about the issue here: https://github.com/carekit-apple/CareKit/pull/676
This preserves the current functionality when `window.tintColor` is available and resorts to `self.view.tintColor` otherwise. Close #1521
> Propagate tintColor if window not available

- ResearchKit.xcodeproj/project.pbxproj
> fix: Building ResearchKit for iPad

- ResearchKitUI/Common/Container Views/Learn More/ORKLearnMoreView.m
- ResearchKitUI/Common/Step/Instruction Step/LearnMore Step/ORKLearnMoreStepViewController.m
- ResearchKitUI/Common/Task/ORKTaskViewController.m
There is an issue leftover from #1519 with `ORKLearnMoreItem` in which the link and the `ORKLearnMoreItem` view has the wrong `tintColor` basically it always uses the default blue. It occurs when constructing a `ORKLearnMoreInstructionStep` and adding a `ORKBodyItem` with `ORKLearnMoreItem` inside of a `ORKOrderedTask`. The link color of "Learn More" and the `tintColor` of the view is incorrect. 
You can see the issue in screenshots below:
> fix: Propagate ORKLearnMoreView tintColor

- ResearchKit.xcodeproj/project.pbxproj
- This sets the "Enable Module Verifier" to true only in release in order to speed up build times.
- Removed target override setting module verification to Yes for all builds
> Set “Enable Module Verifier” flag to “Yes” only in Release build configuration

- ResearchKitSwiftUI/ResearchFormStepContentView.swift
- ResearchKitSwiftUI/ResearchKitSwiftUI/Slider/SliderValueForegroundStyle.swift
- ResearchKitSwiftUI/ResearchKitSwiftUI/Step Views/BodyItemIconForegroundStyle.swift
- ResearchKitSwiftUI/ResearchKitSwiftUI/Step Views/Question Views/Supporting Views/StickyScrollView.swift
- ResearchKitSwiftUI/ResearchKitSwiftUI/Step Views/Question Views/Supporting Views/TextChoiceOption.swift
- ResearchKitSwiftUI/ResearchKitSwiftUI/Step Views/StepIconForegroundStyle.swift
The buttons are hardcoded to blue, preventing the ability to change the color via a modifier. In addition, navigation buttons at the top (e.g. "Cancel") are not hard coded leading to views that don't match when accentColor is passed.
> fix: Use accent color instead of hardcoded blue

- ResearchKitUI/Common/Step/Form Step/ORKFormStepViewController.m
fixes a crash in the `ORKFormStepViewController` when answering the last question in a form, but there's subsequent informational (non-question) sections
the issue here is caused by the fact that the informational sections in the UITableView consist of only a header (which displays the informational content), but no actual cells.
meaning that when you attempt to scroll to the section, it'll try to scroll to a non-existent index path, which'll cause the table view to crash.
we work around this by explicitly handling this situation and adjusting the destination index path to scroll to the section as a whole instead.
> fix crash when answering form question

- ResearchKit/Common/ORKHelpers_Internal.h
Updated the internal helper method ORKLocalizedString() to check if a string key exists in the main bundle localization tables before checking for the key in the ResearchKit localization tables.
Checks for keys in the following priority:
1. "ResearchKit" table in main bundle
2. checks the default localization table in the main bundle 
3. checks the ResearchKit bundle tables
Close: #1601
> feat: Use main bundle localized key/values first if available
