- ResearchKit/ActiveTasks/ORKAccelerometerRecorder.m
- ResearchKit/Common/ORKFormItemCell.h
Reading the code, I've found these unnecessary semicolons and I made the PR to remove them.
> Removed unnecessary semicolons

- ResearchKitTests/ORKAccessibilityTests.m
- ResearchKitTests/ORKChoiceAnswerFormatHelperTests.m
- ResearchKitTests/ORKConsentTests.m
- ResearchKitTests/ORKDataLoggerManagerTests.m
- ResearchKitTests/ORKDataLoggerTests.m
- ResearchKitTests/ORKHKSampleTests.m
- ResearchKitTests/ORKRecorderTests.m
- ResearchKitTests/ORKResultTests.m
- ResearchKitTests/ORKTextChoiceCellGroupTests.m
Cleaned some tests from boilerplate, moved tests fixtures to ```-setUp```
> Cleanup tests

- ResearchKit/ActiveTasks/ORKActiveStepTimer.m
- ResearchKit/Common/ORKStepHeaderView.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKitTests/ORKRecorderTests.m
- ResearchKitTests/ORKResultTests.m
- ResearchKitTests/ORKTextChoiceCellGroupTests.m
> Fix comma inconsistencies.

- ResearchKit/Common/ORKResult.h
- ResearchKit/Common/ORKTableContainerView.m
- ResearchKit/Common/UIApplication+ResearchKit.h
- ResearchKit/Common/UIApplication+ResearchKit.m
- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
There was a crash filling and viewing results in the form sample.
> Fixed Form Sample Crash

- ResearchKit/ActiveTasks/CLLocation+ORKJSONDictionary.m
- ResearchKit/ActiveTasks/ORKAudioRecorder.m
- ResearchKit/ActiveTasks/ORKDataLogger.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/Common/ORKChoiceAnswerFormatHelper.m
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKSurveyAnswerCell.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Common/ORKTextChoiceCellGroup.m
- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
- ResearchKit/Consent/ORKEAGLMoviePlayerView.m
Updating the code to use modern Objective-C syntax.
> Updating to use modern Objective-C syntax.

- ResearchKit/Common/ORKDefines_Private.h
- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
#45 Can be closed when this is merged. Kudos to @steipete for finding this issue.
> Fixed possible double evaluation in the ORKDynamicCast macro

- ResearchKit/Common/ORKTaskViewController.m
- Testing/ORKTest/ORKTest.xcodeproj/project.pbxproj
- Testing/ORKTest/ORKTest/Info.plist
- samples/ORKCatalog/ORKCatalog.xcodeproj/project.pbxproj
- samples/ORKCatalog/ORKCatalog/Info.plist
Addresses what described in https://github.com/ResearchKit/ResearchKit/issues/72
> Make apps universal, remove healthkit requirement

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/ActiveTasks/ORKVoiceEngine.m
- ResearchKit/ActiveTasks/ORKVoiceEngine_Internal.h
- ResearchKitTests/ORKUIViewAccessibilityTests.m
- ResearchKitTests/ORKVoiceEngineTests.m
- ResearchKitTests/UIViewORKAccessibilityTests.m
I have added test for some classes. Please feel free to comment style/naming/etc. because it's hard to get it right without complete guide
> More tests

- ResearchKit/Common/ORKSurveyAnswerCellForPicker.m
Fixes [issue #75](https://github.com/ResearchKit/ResearchKit/issues/75).
> Center pickers on iPad

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKObserver.h
- ResearchKit/Common/ORKObserver.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Common/ORKTaskViewController_Internal.h
- ResearchKit/Consent/ORKConsentSceneViewController.m
- ResearchKit/Consent/ORKConsentSceneViewController_Internal.h
- ResearchKit/Consent/ORKVisualConsentStepViewController.m
- ResearchKit/Consent/ORKVisualConsentTransitionAnimator.m
Deals with problems detailed on [issue #68](https://github.com/ResearchKit/ResearchKit/issues/68).
> Fix visual consent scene scroll

- docs/ActiveTasks/ActiveTasks-template.markdown
> Fix spelling error

- docs/Survey/CreatingSurveys-template.markdown
Remove extraneous quotation mark
> Fix typo in documentation

- docs/Overview/GuideOverview-template.markdown
Use a semicolon instead of a comma.
Also add a newline to the end of the file.
> Fix small grammatical issue

- docs/ActiveTasks/ActiveTasks-template.markdown
This change should improve the table's readability and accessibility.
> Active Task docs: add thead/tbody tags to table

- docs/InformedConsent/InformedConsent-template.markdown
Closes https://github.com/ResearchKit/ResearchKit/issues/120.
> Indicate that consent document must be copied for signature to be applied correctly

- ResearchKit/ActiveTasks/ORKAudioContentView.h
- ResearchKit/ActiveTasks/ORKAudioContentView.m
- ResearchKit/ActiveTasks/ORKAudioStepViewController.m
- ResearchKit/Localized/en.lproj/Localizable.strings
> Alert the user when an audioRecorder generates an error

- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
- ResearchKit/Consent/ORKConsentSignatureController.m
- ResearchKit/Consent/ORKSignatureView.m
- Testing/ORKTest/ORKTest/Info.plist
- samples/ORKCatalog/ORKCatalog/Info.plist
Deals with issues #143 and #144.
> Fix signature view metrics

- ResearchKit/Common/ORKSurveyAnswerCellForScale.m
Fixes [issue #158](https://github.com/ResearchKit/ResearchKit/issues/158).
> Make ORKSurveyAnswerCellForScale constraints static

- ResearchKit/ActiveTasks/ORKActiveStepQuantityView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
Mini pull-request: a prequel to the *memory game* iPad layout fix work.
> ActiveStepQuantityView & SpatialSpanMemoryContentView constraint code whitespace

- ResearchKit/Consent/ORKConsentDocument.m
- ResearchKit/Consent/ORKConsentReviewController.m
Deals with [issue #146](https://github.com/ResearchKit/ResearchKit/issues/146).
> Consent review iPad metrics and margins homogenization

- ResearchKit/ActiveTasks/ORKAudioContentView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/Common/ORKChoiceViewCell.m
- ResearchKit/Common/ORKCustomStepView.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
- ResearchKit/Common/ORKSurveyAnswerCellForNumber.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Common/ORKTableContainerView.m
- ResearchKit/Common/ORKTableViewCell.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Consent/ORKConsentDocument.m
- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentSignatureController.m
The naming inconsistencies between the margin functions were bothering me. This standardizes them.
Merge after [pull request #166](https://github.com/ResearchKit/ResearchKit/pull/166) to avoid conflicts. ;)
> Standardize ORKSkin metric functions

- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryStepViewController.m
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKSkin.m
Deals with [Issue #147](https://github.com/ResearchKit/ResearchKit/issues/147). See issue for comments.
> Fix memory game layout jitter on iPad

- ResearchKit/Common/ORKContinueButton.m
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKStepHeaderView.m
- ResearchKit/Common/ORKTableContainerView.m
- ResearchKit/Common/ORKTextFieldView.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Consent/ORKConsentSignatureController.m
Deals with first part of [Issue #99](https://github.com/ResearchKit/ResearchKit/issues/99).
> Constraints: make sure [super updateConstraints] is always called last

- ResearchKit/Consent/ORKConsentSceneViewController.m
> Present consent "Learn More" content in form sheet

- ResearchKit/ActiveTasks/ORKToneAudiometryContentView.m
- ResearchKit/Common/ORKResult.h
Fixes merge conflicts introduced in [pull request #114](https://github.com/ResearchKit/ResearchKit/pull/114).
> Resolve tone audiometry merge conflicts

- ResearchKit/ActiveTasks/ORKActiveStepQuantityView.m
- ResearchKit/ActiveTasks/ORKFitnessContentView.m
- ResearchKit/ActiveTasks/ORKSpatialSpanMemoryContentView.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
- ResearchKit/Common/ORKStepHeaderView.m
- ResearchKit/Common/ORKTextFieldView.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Consent/ORKSignatureView.m
Makes [pull request #188](https://github.com/ResearchKit/ResearchKit/pull/188)'s fix slightly prettier.
> Avoid using magic number in ORKQuestionStepViewController

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Consent/ORKConsentDocument.h
- ResearchKit/Consent/ORKConsentDocument.m
- ResearchKit/Consent/ORKConsentDocument_Internal.h
- ResearchKit/Consent/ORKConsentSectionFormatter.h
- ResearchKit/Consent/ORKConsentSectionFormatter.m
- ResearchKit/Consent/ORKConsentSignatureFormatter.h
- ResearchKit/Consent/ORKConsentSignatureFormatter.m
- ResearchKitTests/ORKConsentDocumentTests.m
- ResearchKitTests/ORKConsentSectionFormatterTests.m
- ResearchKitTests/ORKConsentSignatureFormatterTests.m
Adds copywriter headers to relevant files from PR #198.
> Fix reverted pr 198

- docs/Survey/CreatingSurveys-template.markdown
A minor edit to one of the example snippets.
> Update ORKFormStep API usage in the example snippet

- samples/ORKCatalog/ORKCatalog/ResultTableViewProviders.swift
- samples/ORKCatalog/ORKCatalog/TextImageTableViewCell.swift
The ORKCatalog changes for the image capture step have been reviewed for sample
code quality. A few minor changes ensue, mainly to simplify the syntax.
> Swift review changes

- ResearchKit/Consent/ORKEAGLMoviePlayerView.m
Fixes consent animation having an incorrect aspect ratio after a rotation.
Also:
- Add guards so GL functions aren't called if OpenGL is not setup.
- Delete program and buffers on dealloc.
> ORKEAGLMoviePlayerView: fix incorrect aspect ratio after rotation

- scripts/plist-to-strings.py
Refactor repeated code to create a function.
> Make plist to strings script DRY

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKDefines.h
- ResearchKit/Common/ORKOrderedTask.h
- ResearchKit/Common/ORKResultPredicate.h
Added some missing `@param` comments and fixed some incorrect ones.
> Fix some erroneous HeaderDocs @param comments

- ResearchKit/Common/ORKImageCaptureCameraPreviewView.m
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKScaleSliderView.h
- ResearchKit/Localized/en.lproj/Localizable.strings
- Annotates the image capture view in an image capture step as an image.
- Adds the slider range description labels to the VoiceOver range description.
> Accessibility updates.

- ResearchKit/ActiveTasks/ORKToneAudiometryPracticeStepViewController.m
Fixes [Issue #235](https://github.com/ResearchKit/ResearchKit/issues/235).
> Tone audiometry: stop playing sound on step suspend

- ResearchKit/Common/ORKImageCaptureView.m
Existing listened for device orientation notifications, rather than status bar orientation.
Status bar orientation is the right one to listen for.
> Issue #234 - Fix rotation behavior on iPad.

- ResearchKit/Common/ORKSurveyAnswerCellForPicker.m
The constraints implementation change updates to correct behavior, but did
not affect the actual bug.
> Fix picker layout centering in certain conditions.

- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKTaskViewController.m
Also: minor variable renames and whitespace conforming.
> ORKURLForRelativePath(): use NSURL methods instead of CFURL's

- samples/ORKCatalog/ORKCatalog/TaskListRow.swift
Fixed renamed identifier reference from #262
> Fix for compile error in #262

- ResearchKit/Common/ORKImageCaptureView.m
Minimum convergence changeset mirroring [PR #265](https://github.com/ResearchKit/ResearchKit/pull/265)'s fix.
> Fix image capture view constraints updating after rotation

- ResearchKit/Consent/ORKConsentLearnMoreViewController.m
> "Learn More" modal views: replace "Cancel" with "Done"  (Fix for #266)

- ResearchKit/Consent/ORKConsentSection.m
Make contentURL work as a bookmark URL.
> Fix test failure in ORKTest

- ResearchKit/Consent/ORKConsentReviewStepViewController.m
Add Vietnamese to the list of such languages for consent review.
> Vietnamese is a family name first language

- ResearchKit/Consent/ORKConsentReviewStepViewController.m
Reverts ResearchKit/ResearchKit#282
> Revert "Vietnamese is a family name first language"

- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKFormStepViewController.m
- ResearchKit/Common/ORKQuestionStepViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
#292
Add a shared method `ORKIsAnswerEmpty(id answer)` to judge if an answer is empty.
Also add a non optional form step in ORKTest to verify this fix.
> Fix issue #292 Value picker in a non optional form allows going to next step

- ResearchKit/Common/ORKStepViewController.m
https://github.com/ResearchKit/ResearchKit/issues/310
> Implementation of issue # 310 - Custom title glitch for bar button items.

- ResearchKit/ActiveTasks/ORKRecorder.m
Added step identifier to ORKRecorder's `logName` to make it more descriptive.
#323
> IOI # 323 - Refactored ORKRecorder's logName

- ResearchKit/Common/ORKQuestionStepViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Show choice cells with nextButton on step has an answer
- Show arrowed choice cells without next button on step has no answer
#294
> Fix issue 294, adaptive UI for non-optional single choice step

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Localized/en.lproj/Localizable.strings
- ResearchKitTests/ORKAnswerFormatTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Exposed the keyboard type property on ORKTextAnswerFormat.
- Added a special ORKAnswerFormat for emails, ORKEmailAnswerFormat.
> IOI # 261 - Exposing keyboard type property

- ResearchKit/Common/ORKStepViewController.h
- ResearchKit/Common/ORKStepViewController.m
Added `hasBeenPresented` method to address issue #336
> Implementation of issue #336

- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
Pass `secureTextEntry` to textField/textView accepts `ORKTextAnswerFormat`
#352
> Expose `secureTextEntry` on ORKTextAnswerFormat

- ResearchKit/ActiveTasks/ORKTowerOfHanoiStep.m
Applying the fix from iOS9 branch onto master.
Reference: https://github.com/YuanZhu-apple/ResearchKit/blob/1ab959d8a8d8df91542a26678279e227615607a9/ResearchKit/ActiveTasks/ORKTowerOfHanoiStep.m
> Secure coding fix for TowerOfHanoiStep

- ResearchKit/Common/ORKTaskViewController.m
- Testing/ORKTest/ORKTest/MainViewController.m
> Implementation of issue #346

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKAnswerFormat.h
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKAnswerFormat_Internal.h
- ResearchKit/Common/ORKScaleRangeImageView.h
- ResearchKit/Common/ORKScaleRangeImageView.m
- ResearchKit/Common/ORKScaleSlider.m
- ResearchKit/Common/ORKScaleSliderView.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
A scale slider that display images at the start/end range of the slider instead of the minimum/maximum number.
> IOI #356 - Scale slider with images.

- ResearchKit/ActiveTasks/ORKAccelerometerRecorder.m
- ResearchKit/ActiveTasks/ORKAudioContentView.m
- ResearchKit/ActiveTasks/ORKDeviceMotionRecorder.m
- ResearchKit/ActiveTasks/ORKReactionTimeViewController.m
- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/Common/ORKBorderedButton.m
- ResearchKit/Common/ORKFormItemCell.m
- ResearchKit/Common/ORKImageCaptureStepViewController.m
- ResearchKit/Common/ORKImageCaptureView.m
- ResearchKit/Common/ORKImageSelectionView.m
- ResearchKit/Common/ORKInstructionStep.m
- ResearchKit/Common/ORKResult.m
- ResearchKit/Common/ORKStep.m
- ResearchKit/Common/ORKSurveyAnswerCellForScale.m
- ResearchKit/Common/ORKSurveyAnswerCellForText.m
- ResearchKit/Common/ORKVerticalContainerView.m
- ResearchKit/Consent/ORKConsentDocument.m
- ResearchKit/Consent/ORKConsentLearnMoreViewController.m
- ResearchKit/Consent/ORKConsentSceneViewController.m
- ResearchKit/Consent/ORKConsentSection.m
- ResearchKit/Consent/ORKConsentSectionFormatter.m
- ResearchKit/Consent/ORKSignatureView.m
- ResearchKit/Consent/ORKVisualConsentStepViewController.m
- Framework Review
- Simplification of Operations
- Performance consolidation
- Performance breaks and returns 
- Code formatting updates in accordance with the provided coding style guide
> Performance, Consolidation of Operations, and Formatting

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Accessibility/ORKLineGraphAccessibilityElement.h
- ResearchKit/Accessibility/ORKLineGraphAccessibilityElement.m
- ResearchKit/ActiveTasks/ORKPSATKeyboardView.m
- ResearchKit/ActiveTasks/ORKTowerOfHanoiTowerView.m
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKPieChartLegendCell.m
- ResearchKit/Charts/ORKPieChartLegendView.m
- ResearchKit/Charts/ORKPieChartPieView.m
- ResearchKit/Charts/ORKPieChartTitleTextView.m
- ResearchKit/Charts/ORKPieChartView.m
- ResearchKit/Charts/ORKRangedPoint.m
- samples/ORKCatalog/ORKCatalog/Charts/ChartDataSources.swift
> Accessibility enhancement for Charts

- ResearchKit/ActiveTasks/ORKTowerOfHanoiTowerView.m
- ResearchKit/Localized/en.lproj/Localizable.strings
> Improve localization string for accessibility of Hanoi Tower

- ResearchKit/ActiveTasks/ORKPSATStepViewController.m
- Improved the naming of the timer
- Used a delay on `ORKActiveStepTimer` to replace the extra `dispatch_after`
- Don't show `-` if the difference between `stimulusDuration` and `interStimulusInterval` is less than timer's resolution (0.05s).
#390
> Fix #390 PSAT Visual mode: digits only appears briefly if set `duration` very close to `interval`

- ResearchKit/Common/ORKHelpers.h
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
- ResearchKit/Consent/ORKVisualConsentStepViewController.m
>  Should adjust PageViewControllerNavigationDirection for RTL

- ResearchKit/ActiveTasks/HKSample+ORKJSONDictionary.m
- ResearchKit/ActiveTasks/ORKRecorder.m
- ResearchKit/Common/ORKHelpers.m
- ResearchKit/Consent/ORKConsentSignature.m
- ResearchKitTests/ORKDataLoggerManagerTests.m
- ResearchKitTests/ORKDataLoggerTests.m
- ResearchKitTests/ORKHKSampleTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
Should use [_recorderUUID uuidString] instead of [_recorderUUID description]
> Fix recorder file naming

- ResearchKit/Charts/ORKDiscreteGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKLineGraphChartView.h
- ResearchKit/Charts/ORKPieChartView.h
Some additional minor *headerdoc* improvements for the charts.
> Charts: additional headerdoc improvements

- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- Testing/ORKTest/ORKTest/Charts/ChartDataSources.swift
Thanks @rsanchezsaez 's  #439 
This is a following up PR to fix a minor issue.
> Use `ORKLocalizedStringFromNumber()`

- RKWorkspace.xcworkspace/contents.xcworkspacedata
Save developer's effort in switching between project files.
> Add a single workspace that includes RK,  ORKTest, and ORKCatalog for convenience

- ResearchKit/Consent/ORKEAGLMoviePlayerView.m
Fix for #455
Root cause: old playerView's dealloc happens on the new EAGLContext(wrong) of new playerView.
Save/Restore EAGLContext in each of the methods which do GL drawing.
This make more than one GLContext lives together.
> Fix consent animation.

- ResearchKit/Consent/ORKConsentSignatureFormatter.m
Dedicated push for #433 issue,I'll close that one
> signature.title exception on null

- RELEASE-NOTES.md
This PR adds a `CHANGELOG.md` file as per [Issue #458](https://github.com/ResearchKit/ResearchKit/issues/458).
It was auto-generated using the very nice [github_changelog_generator](https://github.com/skywinder/github-changelog-generator), and then manually edited to remove irrelevant *closed issues*.
These are the issues I removed (it would be great if we could mark these with either `duplicate`, `question`, `invalid` or `wontfix` labels here on *GitHub*, as that'll cause *github_changelog_generator* to automatically ignore them on subsequent runs):
- htmlReviewContent and makePDFWithCompletionHandler [\#461](https://github.com/ResearchKit/ResearchKit/issues/461)
- Version 1.2 Build Errors in Xcode 6.4 Base SDK iOS 8.4 [\#452](https://github.com/ResearchKit/ResearchKit/issues/452)
- …
> Add CHANGELOG.md

- ResearchKitTests/ORKConsentSignatureFormatterTests.m
`HTMLForSignature:` would throw exception on a nil `signature.title`
> Clear unexpected exceptions from unit tests.

- README.md
Updating the README to remove links to the mailing lists (since they are now discontinued) and add the ResearchKit Forum link.
> Updating README for RK Forum.

- Testing/ORKTest/ORKTest/MainViewController.m
- samples/ORKCatalog/ORKCatalog/Tasks/TaskListRow.swift
This minor PR improves some class and method names by following naming conventions.
> ORKTest: improve some class and method names

- ResearchKit/ActiveTasks/ORKPSATContentView.m
> Fix PSAT progress indicator tint color.

- samples/ORKSample/ORKSample.xcodeproj/project.pbxproj
This PR adds the *ResearchKit* framework to `ORKSample`'s *Embed Frameworks* build phase, otherwise it won't run on devices. ~~It also, adds a custom icon for the new app~~.
> ORKSample fixes

- ResearchKit/Common/ORKChoiceAnswerFormatHelper.m
This PR deals with [Issue #402](https://github.com/ResearchKit/ResearchKit/issues/402).
> [ORKChoiceAnswerFormatHelper] Relax class checking so choice answer formats can be subclassed

- ResearchKit/Charts/ORKGraphChartView.m
Fixes [Issue #589](https://github.com/ResearchKit/ResearchKit/issues/589).
> [ORKGraphChartView] Fix wrong selector check on accessibility

- ResearchKit/Common/ORKOrderedTask.m
This simple fix deals with [Issue #562](https://github.com/ResearchKit/ResearchKit/issues/562).
> [ORKOrderedTask] Validate step identifier uniqueness on init

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKReviewStep.m
- ResearchKitTests/ORKChoiceAnswerFormatHelperTests.m
- ResearchKitTests/ORKTaskTests.m
- ResearchKitTests/ORKTextChoiceCellGroupTests.m
- Testing/ORKTest/ORKTest.xcodeproj/project.pbxproj
- Testing/ORKTest/ORKTest/ORKESerialization.m
- Testing/ORKTest/ORKTestTests/ORKJSONSerializationTests.m
- samples/ORKCatalog/ORKCatalog.xcodeproj/project.pbxproj
- samples/ORKSample/ORKSample.xcodeproj/project.pbxproj
Two things were making the tests to fail
- Duplicate step identifiers in one of the mock tasks.
- Lack of `ORKReviewStep` handling.
> [ORKTestTests] Fix unit tests

- RELEASE-NOTES.md
Fix some typos, rewrite some sentences for clarity and improve formatting.
> [RELEASE-NOTES.md] Improvements

- RELEASE-NOTES.md
> [RELEASE-NOTES.md] Fix a typo

- ResearchKit/Common/ORKAnswerFormat_Private.h
- ResearchKit/Common/ORKResult.h
Mark class available for two Classes.
This is the fix for https://github.com/ResearchKit/ResearchKit/issues/649
> Fix class visibility

- ResearchKit/Common/ORKStepNavigationRule.swift
See [issue 714](https://github.com/ResearchKit/ResearchKit/issues/714)
> Update extension to `ORKPredicateStepNavigationRule` to support Swift 3 and 2.x

- ResearchKit/ActiveTasks/ORKAudioStepViewController.h
- ResearchKit/ActiveTasks/ORKAudioStepViewController.m
Allow for a custom threshold on `ORKAudioStepViewController`.
> Audio ActiveTask View - add ability to define threshold value

- ResearchKit.podspec
Fixes [Issue #642](https://github.com/ResearchKit/ResearchKit/issues/642).
> [Cocoapods] Fix podspec to include swift files

- ResearchKit/Common/ORKPasscodeStepViewController.m
- ResearchKit/Common/ORKPasscodeViewController.h
- ResearchKit/Localized/en.lproj/ResearchKit.strings
- Testing/ORKTest/ORKTest/MainViewController.m
The "forgot passcode" implementation allows us to log out the participant and flush their personal data. The user can then log back in and update their information from the server. Thus, they can safely recover from a situation where the participant has forgotten their passcode.
> Forgot passcode with delegate methods matching existing pattern

- ResearchKit.xcodeproj/project.pbxproj
- ResearchKit/Common/ORKTableStep.h
- ResearchKit/Common/ORKTableStep.m
- ResearchKit/Common/ORKTableStepViewController.h
- ResearchKit/Common/ORKTableStepViewController.m
- ResearchKit/Common/ORKTableStepViewController_Internal.h
- ResearchKit/ResearchKit.h
- Testing/ORKTest/ORKTest/MainViewController.m
- Testing/ORKTest/ORKTest/ORKESerialization.m
`ORKTableStepViewController` is designed to take advantage of the internal class methods used by `ORKFormStepViewController`, `ORKQuestionStepViewController` and `ORKReviewStepViewController` to allow for a consistent UI in a custom implementation.
> Added a general purpose step table view controller

- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKReviewStep.m
> invalid pointer updates (warning fixes)

- samples/ORKSample/ORKSample/HKHealthStore+Queries.swift
- samples/ORKSample/ORKSample/ProfileViewController.swift
Minor typo in function name (mostRecentQauntitySampleOfType).
> Typo in function name

- ResearchKit/Common/ORKVerticalContainerView.m
> Fixed width constraint priority

- ResearchKit/Common/ORKStepNavigationRule.swift
> Changed Predicate back to NSPredicate in accordance with SE-0086

- ResearchKit.xcodeproj/xcshareddata/xcschemes/ResearchKit.xcscheme
- ResearchKit.xcodeproj/xcshareddata/xcschemes/docs.xcscheme
- Testing/ORKTest/ORKTest.xcodeproj/project.pbxproj
- Testing/ORKTest/ORKTest.xcodeproj/xcshareddata/xcschemes/ORKTest.xcscheme
Update to *Xcode 8.1* recommended settings to silence warnings.
> [Projects] Update to Xcode 8.1 recommended settings

- ResearchKit/Common/ORKOrderedTask.m
> Templatized arrays in ORKOrderedTask.m

- ResearchKit/ActiveTasks/ORKAccelerometerRecorder.h
- ResearchKit/Common/ORKResultPredicate.h
- ResearchKit/Common/ORKTaskViewController.h
This PR fixes some (pretty much harmless) typos.
> [Misc] Fix some typos

- ResearchKit/Common/ORKLocationSelectionView.m
> Added gesture recognizer to MapView for ORKLocationAnswerFormat

- README.md
Addresses Issue https://github.com/ResearchKit/ResearchKit/issues/939
The code example in this section of the README now works.
> Update README to reflect new ORK syntax

- samples/ORKCatalog/ORKCatalog/Supporting Files/Info.plist
This prevents a crash during the fitness task.
> Add NSHealthShareUsageDescription key

- ResearchKit/Common/ORKVideoCaptureStep.m
Changed upper duration limit from 120 to 1200 in **ORKVideoCaptureStep**
> Fix for issue #917

- ResearchKit/Common/ORKChoiceViewCell.m
> Fixed bug with ORKTextChoice not using the correct tint color

- ResearchKit/Info.plist
Here's solving issue  https://github.com/ResearchKit/ResearchKit/issues/949
PS: Also, when do you guys intend to release a new version? I noticed 1.4.1 dates from Oct 27, 2016, and some issues we're facing now have been solved in master (i.e.: #825). Is the project dead?
> Update bundle version

- ResearchKitTests/ORKTaskTests.m
- Testing/ORKTest/ORKTestTests/ORKESerialization.m
Fix a few additional *Xcode 9.1* warnings from the tests that I didn't notice.
> [Misc] Fix additional Xcode 9.1 warnings

- ResearchKit/Common/ORKDateTimePicker.m
> Fixes #833. "Date Step - Mismatch between picker.date and what is shown in the UIDatePicker”.

- ResearchKit/Common/ORKTableStep.h
- ResearchKit/Common/ORKTableStepViewController.m
extend ORKTableStepSource to return custom title and view for header in section
> Extend ORKTableStepSource for custom section header

- docs-standalone/reviewing-guidelines.md
Add first draft of the *ResearchKit Reviewing Guidelines*. Comments and suggestions are very welcome!
> [docs] Add first draft of the ResearchKit Reviewing Guidelines

- ResearchKit/Common/ORKHeightPicker.m
- ResearchKit/Common/ORKMultipleValuePicker.m
- ResearchKit/Common/ORKValuePicker.m
- ResearchKit/Common/ORKWeightPicker.m
This is the corresponding PR to issue #1056.
> Added support for Dynamic Types to answer formats that use picker views

- ResearchKit/Common/ORKTextFieldView.m
> fix for #1022

- ResearchKit/ActiveTasks/ORKTappingContentView.m
- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
The iPad 10.5" was added to ORKScreenType to layout for this device
> ScreenType for iPad 10.5

- docs/ChartsAndGraphs/ChartsAndGraphs-template.markdown
- Reposition graph sample screenshot title/caption
- Remove redundant caption
- Added how to update graph data source
- Update syntax in sample code
> Update Chart & Graph Doc

- ResearchKit/Common/ORKPDFViewerStepView.m
Add calls to remove self from the notification center observers after deallocation.
> Add calls to remove self from the notification center observers after deallocation.

- ResearchKit/ActiveTasks/ORKAmslerGridStepViewController.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
Also give it an appropriate label and hint.
Resolves rdar://problem/42293953. Tested on iPhone 7.
> Make the Amsler Grid a direct touch area, so the task can be completed easily by low vision users using VoiceOver.

- ResearchKit/ActiveTasks/ORKSpeechRecognitionContentView.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
Resolves rdar://problem/42294396. Tested on iPhone 7.
> Make the waveform accessible so that low vision users are aware that it is present.

- docs/InformedConsent/InformedConsent-template-ObjC.markdown
- docs/InformedConsent/InformedConsent-template-Swfit3.md
- Re-format screenshots and caption
- Create a Swift version documentation
> Update Consent Doc

- ResearchKit/Common/ORKWebViewStepViewController.m
Updates the webview configuration to allow inline media playback and autoplay.
> Allow autoplay and inline media playback in ORKWebViewStep

- ResearchKit/Common/ORKNavigationContainerView.m
> navigationFooterView should adopt app tint color

- README.md
- docs-standalone/dependency-management.md
Per suggestion in issue #1184 I've updated the dependency management documentation to indicate what tools are necessary. I also added a few badges to the README as found in many GH projects for glanceable information.
> Documentation tweaks

- ResearchKit/Common/ORKSignatureStepViewController.m
- ResearchKit/Consent/ORKConsentReviewController.m
- ResearchKit/Consent/ORKConsentReviewStepViewController.m
> fix for issue #1205

- ResearchKit/Charts/ORKGraphChartView.h
- ResearchKit/Charts/ORKGraphChartView.m
- ResearchKit/Charts/ORKPieChartView.h
- ResearchKit/Charts/ORKPieChartView.m
- Testing/ORKTest/ORKTest/Charts/ChartListViewController.swift
Changes in this PR:
1. Add properties for each of the fonts used in pie charts and graph charts
(IB editable, nil reset, documentation) 
2. Add font changes for each chart type during the cycling in ORKTest
3. Group init code together
> Chart font customization

- ResearchKit/ActiveTasks/ORKAudioRecorder.m
- ResearchKit/ActiveTasks/ORKDataLogger.m
- ResearchKit/ActiveTasks/ORKHealthClinicalTypeRecorder.m
- ResearchKit/ActiveTasks/ORKHealthQuantityTypeRecorder.m
- ResearchKit/ActiveTasks/ORKRecorder.m
- ResearchKit/ActiveTasks/ORKStreamingAudioRecorder.m
- ResearchKit/Common/ORKAnswerFormat.m
- ResearchKit/Common/ORKImageCaptureStepViewController.m
- ResearchKit/Common/ORKKeychainWrapper.m
- ResearchKit/Common/ORKTaskViewController.m
- ResearchKitTests/ORKDataLoggerTests.m
- Testing/ORKTest/ORKTest/MainViewController.m
Homogenize errorOut argument naming and treatment of errors. Slightly improve or fix some edge cases of __autoreleasing errors traversing block limits.
> [Misc] Homogenize errorOut argument naming

- ResearchKit/Common/ORKSkin.h
- ResearchKit/Common/ORKSkin.m
#1255 
according to this issue, I fixed the problem of miscellaneous UI layout inconsistency among devices.
Please check the preview image above for a better notion.
> Ork skin fix

- ResearchKit/Common/ORKImageCaptureStepViewController.m
> Fixed crash related to supported flash modes on certain devices

- ResearchKit/Common/ORKTaskViewController.h
- ResearchKit/Common/ORKTaskViewController.m
solves https://github.com/ResearchKit/ResearchKit/issues/1322
> added missing nullability annotation in one of the initialisers

- ResearchKit/ActiveTasks/ORKTouchAbilityTouch.m
Three new `UITouchPhase`s were added in iOS 13.4.
> Handle new UITouchPhase enumerations.

- docs/Survey/CreatingSurveys-template.markdown
I noticed, that there were a few problems with titles on a "Create Survey" document markdown, so here is a small fix 🙌
> Fix "Create Survey" document formatting

- ResearchKit/Common/ORKSkin.m
Just saw a typo while viewing. Nothing major at all.
> Misspelling of 'Margin'

- ResearchKit/Common/ORKVideoInstructionStepViewController.m
Fixes issue where the play button wasn't present for the VideoInstructionStep.
> Video Instruction Step Now Presents Play Button (#1389)

- ResearchKit/Common/ORKOrderedTask+ORKPredefinedActiveTask.m
- ResearchKit/Localized/en.lproj/ResearchKit.strings
Combines the instructions steps into a single instruction step with body items on iOS 13 and later.
> Updates to predefined range of motion test
